### ISSUE TITLE
Cannot intercept requests from dynamically-created frame , can anyone help ?

### ISSUE THREAD

**Issue by hzzcc** [kettanaito/msw#1006]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hzzcc** [comment]
The frame create like this 
```
var iframe = document.createElement('iframe');
var html = '
<head><script src="/script.js"></script></head>
<body>Iframe</body>
';
document.body.appendChild(iframe);
iframe.contentWindow.document.open();
iframe.contentWindow.document.write(html);
```

@kettanaito

**Comment by hzzcc** [comment]
I think this issue relative to https://github.com/w3c/ServiceWorker/issues/765

**Comment by kettanaito** [comment]
Hey, @hzzcc. What is your expected behavior? What request are we speaking about? Could you please provide more details?

**Comment by hzzcc** [comment]
> Hey, @hzzcc. What is your expected behavior? What request are we speaking about? Could you please provide more details?

Here is the repo, run `yarn start`, you can see logs in devtool
https://github.com/hzzcc/msw_reproduce_example

**Comment by kettanaito** [comment]
Hey, @hzzcc. Thank you for putting together a reproduction repository.

## Root cause

The issue itself is related to how sandboxed iframes inherit the service worker from the parental scope (see https://github.com/w3c/ServiceWorker/issues/765 and https://github.com/w3c/ServiceWorker/issues/1390). According to the W3C decision, such iframes must inherit the worker and be listed in its clients. That, however, doesn't happen. 

This inheritance is required in order for the worker to know that it should control the nested iframe. Without it, the worker doesn't know that the iframe emits any requests and, thus, cannot catch them. That's why you don't get the `GET /user` request from the nested iframe mocked: the worker doesn't know anything about it. 

This may be related to the browser not implementing this inheritance, like this [Chromium bug](https://crbug.com/880768). 

## Solution

There's nothing we can do on the library's side to facilitate this. The service worker behavior implementation is the browser's responsibility. We operate on the higher level, on the already implemented worker spec. Unfortunately, using the iframe scenario like yours isn't possible at the moment due to how browsers implement worker inheritance for such iframes. 

You should be able to have request interception in iframes if you use the `src` attribute instead of `srcDoc`. We do have support for such a use case and it's tested to be functional at the moment. 

```html
<iframe title="frame" src="./frame.html"></iframe>
```

Requests from such nested iframe will be caught and mocked because the `src` iframes inherit the upper-level worker controller.
