### ISSUE TITLE
SyntaxError: Invalid group specifier name in Safari (0.36.0)

### ISSUE THREAD

**Issue by adrianaferrugento** [kettanaito/msw#1018]
## Describe the bug
When loading our app in the Safari browser we see an error in the console which prevents the app from loading.

## Environment

- `msw: 0.36.0`
- `nodejs: 17.2.0`
- `npm: 8.1.4`

> Please also provide your browser version.
Safari v14.1.2

## To Reproduce
Load an app which uses MSW in the Safari browser.

## Expected behavior
App to load normally.

## Screenshots

<img width="424" alt="Screenshot 2021-12-07 at 10 07 30" src="https://user-images.githubusercontent.com/76945696/145010376-a6fef3ce-827a-41a2-90b4-4cfe82c84967.png">

**Comment by kettanaito** [comment]
Hey, @adrianaferrugento. Thanks for reporting this.

I believe the only place where we would use regular expressions is the request route matching. Let me look into this exception in more detail before writing a detailed conclusion.

**Comment by kettanaito** [comment]
No, I was wrong. The issue originates from the following regular expression on our side:

https://github.com/mswjs/msw/blob/93d2226d2ec5d5e5d9dfb6036e4a36e0633cbab6/src/utils/matching/matchRequestUrl.ts#L26-L31

This is where we try to coerce features unsupported by `path-to-regexp` (like wildcards) into expressions that'd still execute as expected. 

## Root cause

Safari doesn't support a Negative lookbehind pattern in regular expressions: `?<!` (see [browser support](https://caniuse.com/js-regexp-lookbehind)). It treats this expression is invalid. 

This is related to https://github.com/mswjs/msw/issues/142, where we've migrated from using negative lookbehind altogether. Let's see if we can rewrite this regular expression not to rely on the syntax unsupported in Safari.

**Comment by adrianaferrugento** [comment]
Amazing, thank you for looking into this!

**Comment by kettanaito** [comment]
Please update to [0.36.1](https://github.com/mswjs/msw/releases/tag/v0.36.1) to get the bug fix in place.
