### ISSUE TITLE
Mocking request cancellation

### ISSUE THREAD

**Issue by SharmaTushar** [kettanaito/msw#1032]
**Is your feature request related to a problem? Please describe.**
I want to make sure that a component aborts up all active network requests when it's unmounted. While the implementation works correctly, I'm unable to mock this.

**Describe the solution you'd like**
I should be able to identify that request was cancelled, either in one of the events, or in the request handler.

**Describe alternatives you've considered**
I tried listening to request end event in the request handler, but that doesn't appear to be supported.

Then I tried capturing request data with server events, and expected requests to end in less than 2500ms, but they don't.
```javascript
it('cancels requests when unmounting', async () => {
  const handler = (req, res, ctx) => {
    return res(
      ctx.delay(2500),
      ctx.status(200),
    );
  };
  server.use(
    ...['get', 'post', 'put', 'patch', 'delete', 'options', 'head'].map(method =>
      rest[method]('*', handler)
    )
  );

  const requests = {};
  server.events.on('request:start', (req) => {
    const { id } = req;
    requests[id] = {
      start: new Date(),
    };
  });

  server.events.on('request:end', (req) => {
    const { id } = req;
    requests[id].end = new Date();
  });

  const { unmount } = render(<UserList/>);
  await new Promise((resolve) => setTimeout(resolve, 500));
  unmount();
  await new Promise((resolve) => setTimeout(resolve, 3000));
  Object.values(requests).forEach(({ start, end }) => {
    expect(end - start).toBeLessThan(2400);
  });
});
```
Output:
```
expect(received).toBeLessThan(expected)

    Expected: < 2400
    Received:   2514
```

**Comment by kettanaito** [comment]
Hey, @SharmaTushar. 

Could you please share how exactly are you aborting the requests in your component? Sharing a reproduction repository for this issue would be great.

**Comment by SharmaTushar** [comment]
Sorry, I thought I'd include the cancellation mechanism as well, but forgot.

```javascript
import axios from 'axios';

const request = ({
  url,
  method = 'get',
  body,
  headers,
  query,
}) => {
  const { CancelToken } = axios;
  const source = CancelToken.source();
  const config = {
    url,
    method,
    data: body,
    headers,
    params: query,
    cancelToken: source.token,
  };

  /**
   * @async
   * @function execute
   * @returns {Promise<any>}
   */
  const execute = async () => {
    try {
      const response = await axios(config);
      const { data, status } = response;
      return { data, status };
    } catch (e) {
      if (axios.isCancel(e)) {
        return { cancelled: true };
      }
      throw e;
    }
  };

  /** @type {Function} */
  const cancel = source.cancel;

  return {
    execute,
    cancel,
  };
};

```
This request function returns two methods - one to initiate the request, and another to cancel it. The `cancel` method is called in `componentWillUnmount` or is returned from `useEffect`.

I will try to create a sample repository at the earliest possible.

**Comment by kettanaito** [comment]
My concern with this is that "request cancellation" is a client-side feature. With MSW, you're describing server-side behavior. I don't think the actual server would know if you cancel a request on the client. I'd be surprised if that is how it works. To my best knowledge, request cancellation is a primarily client-side technique, as you cannot actually cancel the request processing on the server, you can only "short circuit" the established connection from the client. That's why you're having trouble mocking this with MSW—it's not something a server would know in a traditional one-directional data transfer. 

I recommend testing your client-side logic around request cancellation and then stubbing the cancellation hook/function in your integration test to ensure that it's been called. This should be enough to get confidence in the said logic.
