### ISSUE TITLE
Should NetworkError extend TypeError?

### ISSUE THREAD

**Issue by smeijer** [kettanaito/msw#1066]
**Is your feature request related to a problem? Please describe.**
A `fetch()` promise will reject with a TypeError when a network error is encountered or CORS is misconfigured on the server-side ([mdn](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#checking_that_the_fetch_was_successful), but MSW throws a custom type `NetworkError`, which extends `Error`. This makes it impossible to test error handling depending on `instanceof TypeError` checks to handle for network errors explicitly.

```js
catch (error) {
  if (error instanceof TypeError) return doSomething()
  throw error;
}
```

**Describe the solution you'd like**
I think `NetworkError` should extend the more specific `TypeError` instead of `Error`.

```ts
export class NetworkError extends TypeError {
  constructor(message: string) {
    super(message)
    this.name = 'NetworkError'
  }
}
```

**Describe alternatives you've considered**
Add an option to throw specific kinds of errors.

```js
ctx.throw(new TypeError('something went wrong'))
```

**Additional context**
https://github.com/mswjs/msw/blob/2e7ecd87e5568c6e59a408e812535f088498e437/src/utils/NetworkError.ts#L1-L6

https://github.com/mswjs/msw/blob/2e7ecd87e5568c6e59a408e812535f088498e437/src/mockServiceWorker.js#L210-L217

**Comment by kettanaito** [comment]
Hey, @smeijer. Thanks for raising this.

Let's check what class does the network error have when it happens without MSW around. We should adhere to that class in MSW as well. 

> Add an option to throw specific kinds of errors.

Can you tell me more about when do you need this?

It's unlikely that we add such support because it's not a behavior you can expect from a server. On the server there are 2 kinds of errors:

- Intentional. These are communicated per REST API specification via correct response status codes/headers/bodies.
- Unintentional (also known as "things went terribly wrong"). These represent internal exceptions and, while the exception surfaces on the server runtime, the client always receives a generic `500 Internal Server Error` as a representation that there was an unhandled exception on the server. 

That is why when you throw in your request handler (which you can totally do if you need to), those errors will be caught by the library and coerced into `500` responses, including the original error's stack trace for observability.

**Comment by smeijer** [comment]
> Let's check what class does the network error have when it happens without MSW around. We should adhere to that class in MSW as well.

So that would be `TypeError`. If you'd run a fetch while being offline or blocking the URL, the browser throw an Error of instance `TypeError`. That's the use case I need to be able to reproduce, so I can inform the user that something is wrong with the network, and not so much with the entered form data or our server.

```js
fetch('/graphql', { method: 'POST' }).catch((e) => { 
  console.log('is TypeError', e instanceof TypeError);
})
```

https://user-images.githubusercontent.com/1196524/150381407-e033fb8c-5d82-4e6e-ad29-78392edbf1b1.mp4



> Can you tell me more about when do you need this?

I don't need the option to throw any other errors than `TypeError` to be honest. The issue template asked about alternatives, so that would be one. Feel free to ignore that.

**Comment by kettanaito** [comment]
I think there's been confusion about what `res.networkError` does and what `TypeError: Failed to fetch` stands for. Let me clarify below.

The `res.networkError` utility allows you to throw an _intended_ exception during request handling. Examples of such exceptions are CORS error, network/server being down, content security policies errors. Through `res.networkError` you can control the _error message_ propagated to your browser when you make the request. You will see this error as the very first error _before_ `fetch` rejects:

<img width="1174" alt="Screen Shot 2022-01-30 at 12 37 54" src="https://user-images.githubusercontent.com/14984911/151698226-9dc2a093-9c9c-42a5-8b3e-5e36e9e2f17e.png">

Next, the `TypeError: Failed to fetch` is a generic error printed by the request client (`window.fetch` in this case). This error may differ depending on the client, and some may print a generic message while some may not print anything at all. _This_ is the error you get in the `.catch()` block and _this_ is the error that extends `TypeError`.

```js
fetch('https://google.com').catch(e => e.message)
// "Failed to fetch"
```
You can't even access the actual rejection reason like CORS policy violation in the `.catch()` block because `fetch` doesn't expose it to you. 

Now, when mocking network errors via `res.networkError`, you do get the generic `TypeError: Failed to fetch` from `fetch` because that's how it handles any exceptions. You can't really control that error or its message by any means. `res.networkError` will propagate _the preceding_ error message, the one you see before the request promise rejection.

I can confirm that the error you check in the `.catch()` block is `instanceof TypeError`:

<img width="1130" alt="Screen Shot 2022-01-30 at 12 45 34" src="https://user-images.githubusercontent.com/14984911/151698437-4c6994ed-0857-4d39-949e-eb2cc0245ccd.png">

(because that's the generic `fetch` error that's always the same).

**Comment by kettanaito** [comment]
Please let me know if I got your suggestion correctly, @smeijer.

**Comment by smeijer** [comment]
I'm sorry, I looked a bit further into this issue, and I believe the issue originates from `node-fetch`, and not from `msw`. I thought of msw at first, because my logic works in the browser, but MSW seemed to return a different error type.

Making a smaller reproduction lead to another discovery. I basically expect this test to pass:

```js
import { rest } from 'msw';
import { setupServer } from 'msw/node';
import fetch from 'node-fetch';

const server = setupServer(
  rest.get('http://localhost:3000/api', (req, res, ctx) => {
    res.networkError('something went wrong');
  }),
);

beforeAll(() => server.listen());

test('networkError throws an TypeError', async () => {
  await expect(fetch('http://localhost:3000/api')).rejects.toThrow(TypeError);
});
```

The problem is, while the browser's fetch throws a TypeError, `node-fetch` throws a `FetchError` instead. 

So sorry for having wasted your time.

**Comment by kettanaito** [comment]
Hey, @smeijer. Zero time has been wasted! It was a great opportunity for me to refresh my knowledge of client errors. Yeah, in the end, each request client is in charge of what errors it produces. This also makes sense that `node-fetch` would have a difference with `window.fetch` as it's, effectively, a different client based on Fetch API.
