### ISSUE TITLE
Enable a way to run the default behaviour from inside the onUnhandledRequest callback

### ISSUE THREAD

**Issue by james-reed-toshi** [kettanaito/msw#1080]
**Is your feature request related to a problem? Please describe.**
When I want to create a custom `onUnhandledRequest` callback, I want to block a certain url from being flagged, but then I have to re-write the default behaviour in my own code.

**Describe the solution you'd like**
Allow me to hand control back to `msw` for the `onUnhandledRequest` callback.

**Describe alternatives you've considered**
Re-writing the code that already exists in https://github.com/mswjs/msw/blob/ddbc5a7ce30eabc56390eba79e0d260f3a8f598d/src/utils/request/onUnhandledRequest.ts#L180 into my own test code, which would mean it may diverge from `msw` code in future and may not work exactly the same if I don't re-write it correctly.

**Additional context**
We could solve this by adding an extra parameter that is passed to `onUnhandledRequest` called `next`, which will yield control back to `msw`. This would be similar to the `next()` functionality from express.

**Comment by kettanaito** [comment]
Hey, @james-reed-toshi. Thanks for following up on this!

I really like what Rollup is doing with their `onwarn` option:

```js
{
  onwarn(warning, warn) {
    // Suppress a warning sometimes.
    if (condition) return

    // Otherwise, use the default behavior.
    warn(warning)
  }
}
```

I think we should have a similar API exposed in the `onUnhandledRequest` callback:

```ts
worker.start({
  onUnhandledRequest(request, message, print) {
    // Ignore unhandled request warnings/errors that
    // originate from the static assets.
    if (request.url.href.includes('/static')) {
      return
    }

    // Otherwise, warn/error as usual.
    print(message)
  }
})
```

Since our option can produce both warnings and errors, I'd lean towards neutral `message` and `print` argument names (at least for the examples, people can call them anyhow they find comfortable). 

Would you be interested in opening a pull request with this feature?
