### ISSUE TITLE
Option to call event.respondWith only if we have registered handler for this request

### ISSUE THREAD

**Issue by crutch12** [kettanaito/msw#1082]
**Is your feature request related to a problem? Please describe.**
A lot of requests are completed with warning
```
Warning: captured a request without a matching request handler
```
because MSW calls `event.respondWith` almost for every request

**Describe the solution you'd like**
It would be really great, if we could configure `worker.start()` with `bypassUnhandledPath`/`bypassUnknownPath` option
```
worker.start({ bypassUnknownPath: true })
```

Or with some `bypass` function, where I could write own match test
```
const handlers = [] // MSW handlers
const match = (path, url) => { /* ... */ }
worker.start({
  bypass: (req) => {
    const foundHandler = handlers.find((handler) => match(handler.info.path, req.url));
    return !foundHandler;
  },
});
```

**Describe alternatives you've considered**
I've added this code to `fetch` listener in `mockServiceWorker.js`
```js
// Bypass static files (.js/css/woff2/etc).
if (new URL(request.url).pathname.match(/\.(.*)$/)) {
  return;
}
```
So at least now I ignore static files. But this is not enough for me.

**Additional context**
I'm not afraid about warnings, I can disable them.
In fact I'm afraid of Chrome's "network" tab, where I see a lot of XHR requests intercepted with MSW.
But truly these request are `css/js/woff2/html/..etc`. And I would like to not intercept them with MSW at all.
![image](https://user-images.githubusercontent.com/19373212/151579879-9a708f51-200e-4385-8fa7-f235b9f06527.png)

**Comment by kettanaito** [comment]
Hey, @crutch12. 

That's an interesting proposal. Right now MSW intercepts _all_ requests, regardless of whether they are meant to be mocked or not. That's done because the worker doesn't control the criteria for the interception, the client-side part does (your handlers). 

From my testing, the `fetch` event handling in Service Worker was quite interesting. If I recall correctly, your listener function must be synchronous. Any asynchronous logic must be put inside `event.respondWith` as it accepts a Promise. The action of retrieving the matching summary from the client-side thread is asynchronous, so it means you can't do something like this:

```js
self.addListener('fetch', async (event) => {
  const result = await findMatchingHandler(event.request)

  if (!result) {
    return 
  }

  event.respondWith(toResponse(result))
})
```

All sorts of terrible things will happen if `event.respondWith` is not called synchronously. You can give this a try to prove me wrong, though, it's been a while since I've experimented with the request flow in the worker. 

Overall, I'd absolutely love not to handle requests that don't have request handlers for them. But I don't think it's possible given the asynchronous nature of that check and the synchronous nature of the `fetch` event handler. 

I will close this for now, but anyone is welcome to share their insights into this.

**Comment by crutch12** [comment]
@kettanaito but we could do this in `mockServiceWorker.js`
```js
const registeredHandlerPaths = []; // string[]

self.addEventListener('message', ev => {
  const message = JSON.parse(event.data);
  
  if (typeof message === 'object') {
    switch (message.type) {
      case 'MOCK_ACTIVATE': {
        registeredHandlerPaths.push(...message.payload.paths) // save registered paths
        break;
      }
    }
  }

  // ...
})

self.addEventListener('fetch', ev => {
  const match = (url, paths) => { /* ... */ }

  if (!match(ev.request.url, registeredHandlerPaths)) {
    return;
  }

  // ...
})
```

So client will emit registered paths on `worker.start()`
And `mockServiceWorker.js` may accept those paths and bypass if request doesn't match

**Comment by kettanaito** [comment]
@crutch12, performing request matching in the worker is not very efficient. That's what we used to do a few years back and we've migrated from it to give users support to change handlers on runtime. Even if we did, we'd have to synchronize any handler changes with the worker, which is an asynchronous action. 

I see close to no disadvantage of letting the worker handle all requests. Any outgoing request is ethier responded to with a mock (given there's a matching handler that produces one) or performed as-is via `fetch(event.request)`. 

I also think it's good to keep the handlers as the only source of control over the request matching. That's why I'm against options like `excludeRequests` and alike that would introduce unnecessary complexity to the request matching flow.

**Comment by crutch12** [comment]
@kettanaito I agree with this point.
But I can't stand this mess in Network tab :)
So for my projects I will use `bypassHeader` and add some skip logic

**Comment by crutch12** [comment]
Btw
`'x-msw-bypass': false` works differently in `mockServiceWorker.js` and main lib

Because `mockServiceWorker.js` checks for `'true'`
But main lib checks for header existence (it skips even `x-msw-bypass: false`)

**Comment by kettanaito** [comment]
@crutch12, still worth stating that I'm open to suggestions on this, just as long as we can support the current request handling flow. I'd much prefer for the unhandled requests not to trigger a new Fetch call like they do at the moment. I just wasn't able to craft the worker in that way given the limitations of the `event.respondWith`. But I do encourage you, or anybody reading this, to try, you may succeed in that.

**Comment by kettanaito** [comment]
A great find regarding the difference in the `x-msw-bypass` header! I've opened an issue about it https://github.com/mswjs/msw/issues/1085. @crutch12, could you be interested in helping us fix it? I'll assist you during the code review and make sure we cover this behavior difference. Thanks.

**Comment by evisong** [comment]
> But I can't stand this mess in Network tab :)

Just FYI, in Chrome Devtools, Network tab, you may add `-is:service-worker-initiated -is:service-worker-intercepted` to filter out service worker requests. Much cleaner after that.
