### ISSUE TITLE
axios upload progress not working when msw enabled

### ISSUE THREAD

**Issue by iamyoki** [kettanaito/msw#1101]
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | ^0.36.3   |
| browser | 98.0.4758.80     |
| OS      | Macos 11.6     |

## Problem
Upload file using axios when msw enabled, the onUploadProgress event won't be called.

## See problem in this codesandbox example
https://codesandbox.io/s/msw-uploadprogress-not-working-mf4ei?file=/src/App.jsx

**Comment by kettanaito** [comment]
Hey, @iamyoki.

If you try uploading something using the sandbox you've attached, you will see the following warning in your browser's console:

```
index.js:27 [MSW] Warning: captured a request without a matching request handler:

  • POST /upload

If you still wish to intercept this unhandled request, please create a request handler for it.
Read more: https://mswjs.io/docs/getting-started/mocks
```

MSW notifies you that you haven't defined any [request handlers](https://mswjs.io/docs/basics/request-handler) to process `POST /upload`. Thus, your app performs the request as-is and since there's no such endpoint, the upload fails. 

## Step 1: Define the `POST /upload` request handler

```diff
import axios from "axios";
+import { setupWorker, rest } from "msw";
import "./styles.css";

// with msw enabled, upload progress won't be called
// comment below then refresh the page, upload progress will works fine
if (process.env.NODE_ENV === "development") {
  setupWorker(
+   rest.post("/upload", (req, res, ctx) => {
+     return res();
+   })
  ).start();
}
```

Restart the sandbox. Now, uploading files will print a log in your console that the associated request has been captured and its response has been mocked:

<img width="821" alt="Screen Shot 2022-02-15 at 12 29 12" src="https://user-images.githubusercontent.com/14984911/154053543-5e7b6f69-9917-4c8a-a401-cef4b8ffeb49.png">

Hey, but where is the `onUploadProgress` log?

## Step 2: Emulate upload progress

I did a quick search on the web whether Service workers can emulate upload and haven't found anything. If you find it, please post it here for others to see. 

The idea is to respond to the `POST /upload` as an actual server would respond. 

> It's also worth mentioning that for Node.js runtime MSW doesn't currently support the `upload` events (see https://github.com/mswjs/interceptors/issues/187).
