### ISSUE TITLE
Support the native "fetch" in Node.js 17

### ISSUE THREAD

**Issue by antoinerey** [kettanaito/msw#1113]
## Environment

| Name | Version      |
| ---- | ------------ |
| msw  | 0.38.1       |
| node | 17.5.0       |
| OS   | MacOS 12.0.1 |

## Request handlers

```js
import { setupServer } from 'msw/node'
import { rest } from 'msw'

const server = setupServer(
  rest.get('https://hello.world', (request, response, context) => {
    return response(
      context.status(200),
      context.json({ hello: 'world' }),
    )
  })
)

server.listen()
```

## Actual request

```js
const response = await fetch('https://hello.world')
const data = await response.json()

console.log(data)
```

## Current behavior

Running the above setup using native fetch in node 17.5.0 (using the `--experimental-fetch` flag) does not work as expected. Requests are not intercepted, and origins (in this case https://hello.world) are hit.

## Expected behavior

Intercepting requests, as usual. 😁

While this issue uses a "bug" template, I believe that `msw` simply does not support native node.js `fetch` yet. Are there any roadmaps I may watch to know if that's already work-in-progress?

**Comment by kettanaito** [comment]
Hey, @antoinerey. Thanks for reporting this. 

Yeah, you're right saying MSW does not have official support for native `fetch` in Node.js. Moreover, the latest official Node.js version we support is `12.22.0`:

https://github.com/mswjs/msw/blob/1a7bc36d98e0fa0d0fa1c9da6d7dd40605f239ca/.nvmrc#L1

It doesn't mean you can't use the library with newer versions. It only means that our entire testing suite runs against the Node.js version specified in `.nvmrc`, which makes it the latest officially supported version. 

## Native fetch support

As with other requests in Node.js, supporting native `fetch` would imply analyzing how it works under the hood. Since it's not being intercepted right now, I can assume that it doesn't use `http`/`https` internally, and, perhaps, constructs a `ClientRequest` directly. 

If anybody is willing to dive into the Node.js source and write a summary on how `fetch` is implemented there, they would be doing 50% of the work necessary to support it in MSW.

**Comment by BboyKeen** [comment]
@kettanaito I can have a first look at the fetch implementation.

However it seems there are two packages to look at :
- the node-fetch which can be used provide the fetch API server side before Node 17.5 (I think a lot of projects use it)
- the Node.js source in which fetch has been added as global in 17.5

Which one are you interested in ?

**Comment by antoinerey** [comment]
On my side I'm successfully using `msw` with `node-fetch` already. It works exactly as expected! Since `node-fetch` provides a polyfill built on top of existing node modules, I believe that `msw` is able to retrieve the necessary primitives, and thus intercept requests.

However, this is another story when it comes to the native fetch implementation added in node 17.5.0. The underlying primitive must be different, and thus `msw` does not know how to work with those.

I can't answer for @kettanaito, but I would say that this issue is focused on the native fetch implementation, introduced in node 17.5.0.

**Comment by BboyKeen** [comment]
Interesting.
Which version of Node.js are you using ?

MSW.js works using Node.js 12 but using Node.js 16, our server side interceptors don't work.

In the deps, I can see we're using node-fetch 2.6.7

**Comment by antoinerey** [comment]
I'm currently using node 17.5.0 because I just migrated from native fetch to node-fetch, but I believe it works on node 16.x.y as well.

**Comment by cmolina** [comment]
Nodejs is using [undici as fetch implementation](https://github.com/nodejs/node/blob/master/deps/undici/undici.js#L914;L951); which internally uses the `tls` and `net` modules.

**Comment by kettanaito** [comment]
> I can't answer for @kettanaito, but I would say that this issue is focused on the native fetch implementation, introduced in node 17.5.0.

You're absolutely correct.

MSW supports interception of any requests made via `ClientRequest`, which includes `node-fetch`. The native `fetch` is not implemented via `ClientRequest` and that's why it's not being intercepted. 

> Nodejs is using [undici as fetch implementation](https://github.com/nodejs/node/blob/master/deps/undici/undici.js#L914;L951); which internally uses the tls and net modules.

What a find, @cmolina! Could you please link us to the place where native `fetch` relies on undici? 

This may be a big moment to finally make undici support happen in @mswjs/interceptors. The goal is still to find the proper low-level surface to augment. `tls` and `net` are too low-level, I think, but we may look into them nonetheless.

**Comment by cmolina** [comment]
@kettanaito you can see the PR where `fetch` was added: https://github.com/nodejs/node/pull/41749

**Comment by kettanaito** [comment]
Fantastic, @cmolina! For posterity: see [this](https://github.com/nodejs/node/pull/41749/files#diff-b458343641320fd09327e8c48979391307012f67a1b0f12707aa81764193e58bR156-R157). 

So it appears native `fetch` support should be implemented through Undici support (see https://github.com/mswjs/interceptors/issues/159). We already have some tests added by one of our contributors in https://github.com/mswjs/interceptors/pull/180 but the work around analyzing how to best intercept undici requests and implementing the interceptor still remains. 

I will close this issue as there's no additional work needed for fetch specifically, only to support undici (see the linked ticket for that).
