### ISSUE TITLE
Headers is undefined when not handling request

### ISSUE THREAD

**Issue by kentcdodds** [kettanaito/msw#1120]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.38.1   |
| node | 16     |
| OS   | macOS     |

## Request handlers

```js
import { setupServer } from 'msw/node'

const server = setupServer()

server.listen()
```

## Actual request

I'm not making the request, the AWS SDK is. The line that's breaking is this one though:

https://github.com/aws/aws-sdk-js/blob/6cf8513d4012e3bc07330c523cf10f45ce807ff5/lib/event_listeners.js#L412

## Current behavior

When I install msw and use interception without providing any handlers, the `headers` object is `undefined`. If I add a `console.log` of the `resp.httpResponse` in the AWS SDK code, I get this:

<img width="810" alt="image" src="https://user-images.githubusercontent.com/1500684/155796035-74119431-f84b-4bd1-883c-f0a6568ec26c.png">

Downgrading to MSW@0.36.8 resolves this issue

## Expected behavior

I expect the headers to exist. I really expect the entire request to happen without any change when I don't handle the request.

**Comment by kettanaito** [comment]
Hey, @kentcdodds. Thanks for reporting this!

The issue seems related to https://github.com/mswjs/interceptors/issues/212. Node 12 is the latest officially supported version for MSW. We will upgrade to newer versions soon, as 12 is a rather old one at this point. 

I'm curious to know what changed in 16 that `headers` are not present anymore. I suspect that `PassThrough` that we use to clone `IncomingMessage` now behaves differently. I'd appreciate any input and help on this from anybody interested.

**Comment by trevoro** [comment]
I think the issue is that in Node 16 the headers are on the prototype and in Node 12 they're on the instance. When a node interceptor clones a message, it only clones the object instance values and not the prototype values. 

https://github.com/nodejs/node/blob/v12.x/lib/_http_incoming.js#L61
https://github.com/nodejs/node/blob/v16.x/lib/_http_incoming.js#L107-L124

**Comment by kettanaito** [comment]
Yeap, @trevoro, that's the case. I like your initiative to update the supported Node.js version. That will include updating how we handle `headers` as well.
