### ISSUE TITLE
Can't override existing handler (worker.use)

### ISSUE THREAD

**Issue by florianmatz** [kettanaito/msw#1124]
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.38.1   |
| browser | Chrome     |
| OS      |  Mac OS     |

I'm trying to mock out a Auth-Flow, where I want to change a handler dynamically on /login-Route.
The component mounted on /login should change the existing handler from status 401 to 200.

However, worker.use(...) does not override. It seems to ADD another handler. If I log worker.printHandlers(); I see two handlers. One with the desired status of 200, but still a handler returning 401. 

Both have the same url (/auth), but only the last one (401) seems to take action in the end, so I can't mock out my flow.

## Request handlers

```ts
import { SetupWorkerApi, setupWorker, rest } from 'msw';

let wrk: SetupWorkerApi = {} as SetupWorkerApi;

// Conditionally setup msw to keep it out of vite production bundle
if (import.meta.env.DEV) {
    const handlers = [
        rest.get('/auth', (_req, res, ctx) => res(ctx.status(401))),
    ];

    // Configure a Service Worker with the given request handlers
    wrk = setupWorker(...handlers);

    // Store msw on window to access it in e2e-test
    window.msw = {
        worker: wrk,
        rest,
    };
}

export const worker = wrk;
```

## Login component, that should change the /auth-handler

```ts
const Login = () => {
    const [workerChanged, setWorkerChanged] = useState<boolean>(false);

    useEffect(() => {
        const { worker, rest } = window.msw; 
        worker.use(
            rest.get('/auth', (req, res, ctx) => res(ctx.status(200)))
        );
        worker.printHandlers();
        setWorkerChanged(true);
    }, []);

    return workerChanged ? <Navigate to="/" /> : null;
};
```

## Current behavior

Override not working, initially described. The following screenshot shows the two handlers logged with worker.printHandlers();

<img width="665" alt="image" src="https://user-images.githubusercontent.com/4760056/155894054-f75ab498-ce66-4cd2-ab6e-62d2a438666f.png">

## Expected behavior

* Handler should be overridden, not added. 
* Handler should return the desired 200 status
* worker.printHandlers(); should only show ONE handler

May be the same issue like in #1084.

I made sure I have only one MSW-instance running, at least I only have one "Mocking Enabled"  log.
Using vite as a bundler (HMR in dev mode) btw.

**Comment by florianmatz** [comment]
Addition: What I found out, if I add a button, that calls worker.use... in a function, I can even add more handlers. It is basically like adding them up.

**Comment by kettanaito** [comment]
Hey, @florianmatz. 

The `.use()` method has always prepended a request handler. We do not maintain handler identity to provision overrides, and those are not really needed. MSW resolves handlers by order of definition, and `.use()` prepends a handler to the handlers list. So, if a newly added handler matches a request it will be used instead, which for you is perceived as an override. 

You can also provide a [one-time override](https://mswjs.io/docs/api/setup-worker/use#one-time-override) by using `res.once(...)` in your resolver function. 

> There's the [`.resetHandlers()`](https://mswjs.io/docs/api/setup-worker/reset-handlers) as well to remove _all_ runtime handlers you've added via `.use()` at any point in time. 

Having 2 handlers for the same URL after using `worker.use()` is the expected behavior. Once you add the runtime handler (the one that responds with 200 OK), any requests matching `GET /user` will receive a 200 OK response because the newly added handler matches those requests. If they don't, chances are requests is not matching or the handler does not return a mocked response (either way you should get a warning in the console about this, or see the lookup logic fall through to the 401 handler). If you don't wish for 200 OK response to stay forever, consider using `res.once()` as above.

**Comment by florianmatz** [comment]
Thank you for the fast reply. Found my issue^^.

**Comment by kettanaito** [comment]
@florianmatz, glad to hear that! Could you please share what it was here for posterity?

**Comment by florianmatz** [comment]
I changed the location of the app, but not with the browser router. That resulted in a complete refresh and thus creating a weird race condition between a useEffect and setupWorker.

**Comment by ravicious** [comment]
Just for posterity, the comments in this thread helped me understand that the way to do a one-time override with the `worker.use` API is to do something like this:

```javascript
worker.use(
  rest.get('/path', (req, res, ctx) => {
    return res(ctx.text('Response for the 3rd+ request'));
  })
);
worker.use(
  rest.get('/path', (req, res, ctx) => {
    return res.once(ctx.text('Response for the 2nd request'));
  })
);
worker.use(
  rest.get('/path', (req, res, ctx) => {
    return res.once(ctx.text('Response for the 1st request'));
  })
);
```

I was originally googling how to return a different response for subsequent requests with msw, then I found th eone-time override section in the docs and finally landed in this issue when trying to figure out how to use it with `worker.use`.
