### ISSUE TITLE
Automated releases are failing

### ISSUE THREAD

**Issue by jbergstroem** [kettanaito/msw#1135]
It seems that the automated release procedure is failing due to an issue with tests: https://github.com/mswjs/msw/actions/runs/1913054918

**Comment by kettanaito** [comment]
Hey, @jbergstroem. Thanks for pointing this out. 

I've had a similar issue with `semantic-release` on other repos. I've discovered that running tests from within the semantic release pipeline is often flaky, for whichever reason. The tests are otherwise passing reliably both locally and on CI when run standalone (i.e. in a separate step).

What I did is I moved tests into a separate step preceding the release and it seemed to have solved the issue. I think this is what I will do with this release workflow as well.

**Comment by jbergstroem** [comment]
> I've discovered that running tests from within the semantic release pipeline is often flaky, for whichever reason. 

It "may" have happened to me as well. Perhaps - since each PR is tested - the assumption that the `main` branch is "green" can be made? If anything else I'm sure you test well enough locally..

**Comment by kettanaito** [comment]
Yeah, the assumption can be made if it acts as a condition for the release to happen. It's possible to make one workflow depend on the outcome of another workflow in GitHub actions **but** that won't work with cron jobs. I think that's also fair, as when scheduled, releases will happen outside of the default merge cycle, so it has no cost to run build/tests once more, right before the release. 

> If anything else I'm sure you test well enough locally.

Nae, don't take my word for it.

**Comment by kettanaito** [comment]
https://github.com/mswjs/msw/commit/9b5fa82e1fc00e13d49319edbc29542c2ab28890 should solve this.
