### ISSUE TITLE
Importing MSW leaks the Typescript declarations of Node.js globally

### ISSUE THREAD

**Issue by spking11** [kettanaito/msw#1168]
## Describe the bug

I've seen #897, but I am still confused because of the unexpected global @types/node. Even there are no import in other typescript files, and I have tried the "[types](https://www.typescriptlang.org/tsconfig#types)" option in TSConfig which doesn't work. I am sorry that I am just a rookie in this field, I can't understand why this happened and can't be sure whether it's msw's problem or not. Please give me some help. Greatly appreciated.

## Environment

- `msw: 0.39.1`
- `typescript: 4.6.2`

## Reproduction repository

https://codesandbox.io/s/nnn2zz

## Reproduction steps

```
npm i
npx tsc
```

## Current behavior

no error

## Expected behavior

`src/index.ts:1:13 - error TS2304: Cannot find name 'global'.`

**Comment by kettanaito** [comment]
Hey, @spking11.

I've checked your sandbox and you had an invalid `tsconfig.json` file. Trailing commas are not allowed in JSON. 

Once you fix the config file, I see no issues and the `console.log(global)` is printed to the console.

```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "es6",
        "moduleResolution": "Node",
        "strict": true,
        "isolatedModules": true,
        "outDir": "dist",
        "typeRoots": [],
        "types": [],
        "lib": [
            "ES6",
            "DOM"
        ]
    },
    "include": [
        "src/**/*"
    ]
}
```

<img width="586" alt="Screenshot 2022-03-18 at 11 44 37" src="https://user-images.githubusercontent.com/14984911/158989098-8bc10676-2161-4cf8-9b0b-e0bf261660a3.png">

## TypeScript version

I've noticed you are using `"typescript": "^4.6.2"`. Please note that MSW officially supports only TypeScript 4.2. Each minor version of TypeScript contains breaking changes, so we cannot guarantee the library will work 4 de-facto major releases ahead. 

I can run `tsc` in your project in `"typescript": "4.2.x"` without issues:

```sh
$ tsc
✨  Done in 1.37s.
```

## About `@types/node`

MSW depends on `@types/node` as a dev dependency. That package never ends up on our users' machines. 

The issue you're experiencing is not caused by MSW leaking some type definitions. It's because by you missing the `@types/node` (or similar) type definition for your project to annotate `global`.

**Comment by spking11** [comment]
Hey, @kettanaito, thank you for your reply!

Apologize for letting you misunderstand what I mean. I just don't want node's types in other modules without import. I do as your reply, but still have node's  global type as long as import `msw`.
Happily after trying so many times and learning typescript, I find out the real reason. Just because [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0013a7b3f504b8c39e650c49a633efbee1db79af/types/set-cookie-parser/index.d.ts#L7) in `@types/set-cookie-parser` cause tsc to load  `@types/node` and bring its global declaration.
It's not problem of `msw`, just deficiency of typescript. And many people have encountered [this kind of problem](https://github.com/microsoft/TypeScript/issues/37053).
Thank you again for your patience, I'm just confused by these complicated tools.

**Comment by spking11** [comment]
> I've checked your sandbox and you had an invalid `tsconfig.json` file. Trailing commas are not allowed in JSON.

But I can compile with the trailing commas `tsconfig.json`, it seems be tolerant with trailing commas.

**Comment by kettanaito** [comment]
I'm sorry for not looking deeper into this. Thank you for explaining the issue! 

Frankly, we don't have the means to control what global types get exposed, especially when it comes to fourth-party dependencies requiring those types (like `@types/set-cookie-parser`). I understand this is not great but I don't see how we can manage this on the library's level. 

Perhaps once we do have the means, we can reconsider this!
