### ISSUE TITLE
Request handlers doesn't intercept the fetch calls

### ISSUE THREAD

**Issue by tonykhaov** [kettanaito/msw#1226]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v18.0.0 v18.1.0

### Reproduction repository

https://github.com/tonykhaov/react-vitejs-template

### Reproduction steps

git clone the repo
git checkout to `msw-bug-node-18`
use node v18 (run `nvm use node`)
run `yarn install`
run `yarn test:watch fetch`

you can debug it in `fetch.test.tsx`

### Current behavior

MSW doesn't intercept fetch calls with node v18. The bug doesn't not seem to come from node's fetch because I can fetch real endpoints. And I put a console.log in the `server.use(rest.get)` and the console.log is never called. I guess it may come from there!

But when using node v17 with polyfill everything works fine.

### Expected behavior

rest.get callback from l.13 in `fetch.test.tsx` should be called when using node v18.

**Comment by kettanaito** [comment]
Hey, @tonykhaov. Thanks for reporting this.

Could you please try this on Node.js 14/17? I wonder if it's something Node.js 18 introduces that breaks things for us. I've quickly checked the HTTP module and found no breaking changes. It must be something else. 

> The bug doesn't not seem to come from node's fetch because I can fetch real endpoints.

It's definitely not a bug in Node.js but it may be an internal change that breaks things for us.

I've noticed you're speaking of using native `fetch` in Node.js. That's likely to be the root cause: MSW doesn't support native `fetch` at the moment (see #1113, since `fetch` uses `undici`, also see https://github.com/mswjs/interceptors/issues/159). As we have issues tracking this, I'm closing this one. 

I don't have time capacity to look into this, so if you're willing to land a hand and explore `undici` interception—I'd be grateful. You can count on me during code review.

**Comment by tonykhaov** [comment]
Hey I'm coming back to you, it took me a couple days and I found a fix but I have no idea how to fix in the real codebase.

On Node 14 & 17 everything works well without this. But for Node 18:

In my project: [tonykhaov/react-vitejs-template](https://github.com/tonykhaov/react-vitejs-template), I passed `interceptFetch` (from `var Fetch = require('@mswjs/interceptors/lib/interceptors/fetch');`) as an argument to `createSetupServer()` in `node_modules/msw/node/lib/index.js`
![image](https://user-images.githubusercontent.com/53958746/167437120-a0683bc8-a0db-4d9d-8fbc-6b3f28db1080.png)

And then in `node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js`
I changed window.fetch to `global.fetch`
![image](https://user-images.githubusercontent.com/53958746/167437471-0b0c6398-44d8-412b-b61d-b3c2eba609e3.png)

And now the fetch request is intercepted by the server and my test passes.
![image](https://user-images.githubusercontent.com/53958746/167437623-5cc05cb3-cf9f-40c4-8cfe-ecad1f21f725.png)

Hope it helps!

**Comment by kettanaito** [comment]
Hey, @tonykhaov. Thanks for looking into that! 

So the main change is rewriting `global.fetch` and not `window.fetch`. That's interesting. Please, I don't have time to see if this change would be compatible with our tests, but can I ask you to open a pull request to [this line](https://github.com/mswjs/interceptors/blob/425b069ee67eb3e9f3afc84613c772dc02f7326f/src/interceptors/fetch/index.ts#L31) that'd implement it? Let's see if it's compatible with our tests, and if it is, I see little objection to merging it. 

Regarding the addition of `interceptFetch` to `createSetupServer`, that requires more looking into. Your change fixes the issue because in Node.js 17+ there's, in fact, a global `fetch`, which is not implemented by `ClientRequest`, compared to libraries like `node-fetch`. It should be safe to add `interceptFetch` here but let me assess all the implications of this change (adding a test or two would also be a good idea).
