### ISSUE TITLE
(v.0.42) Error - Invariant Violation: Failed to respond  request: the "request" event has already been responded to 

### ISSUE THREAD

**Issue by 7iomka** [kettanaito/msw#1271]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v16.15.0

### Reproduction repository

https://github.com/7iomka/next-with-msw-and-effector

### Reproduction steps

yarn add msw@latest
yarn dev

### Current behavior

```
error - Invariant Violation: Failed to respond to "GET http://localhost:3000/backend-api/xxxx" request: the "request" event has already been responded to.
    at setupServerListener (************/node_modules/msw/lib/node/index.js:1249:17) {
```

### Expected behavior

All works as in v0.38.0

**Comment by kettanaito** [comment]
Hey, @7iomka. Thanks for reporting this. 

This error means that there are two interceptors responding to the same request at the same time. That is no-op, and so the error propagates this issue to the consumer. 

Your setup seems to be good, I'll try forking it and see what's going on.

**Comment by AustineChi** [comment]
I am having the same issue., with a similar setup. is there any solution to this yet @kettanaito

**Comment by kpatticha** [comment]
same here, I use 0.42.1

**Comment by kettanaito** [comment]
Hey, @AustineChi. No, not yet. I can use your help looking into this, so running the tests with a `DEBUG=*` variable may provide us with some additional context.

**Comment by leonardmns12** [comment]
having same issue here

**Comment by sauldeleon** [comment]
I can confirm same problem, and this is not happening in `0.41.1`

It started in our case with `0.42.0` and `0.42.1`

**Comment by Danny-A** [comment]
Also having this issue at `0.39.2`

**Comment by 95th** [comment]
Got the same issue.. Will look into the debug logs

**Comment by 95th** [comment]
So apparently, the `NodeClientRequest` is emitting one event but in `createSetupServer.ts`, the event is received twice:
```js
interceptor.on('request', async function setupServerListener(request) {
```
Looking further

**Comment by 95th** [comment]
It was two test files running the mock server  in parallel

**Comment by Michael-M-Judd** [comment]
> It was two test files running the mock server in parallel

Yep, I noticed this as well. I didn't even need to run `server.listen()` in my jest tests -  it seems to have already been listening without the call. It works fine in browser for me.

**Comment by kettanaito** [comment]
> Yep, I noticed this as well. I didn't even need to run server.listen() in my jest tests

This sounds like an issue. I did a quick check and we're still calling `interceptor.apply()` within the `listen()` method so there should be no interception prior to that. Perhaps you have multiple parallel tests and that's where the state leaks between them? 

> It was two test files running the mock server in parallel

May be the case. Can you please try running your tests sequentially to A/B this? With Jest it'd be `--runInBand`. I don't think MSW supports parallel test runs (yet) although I was hoping the event-driven architecture would enable that.

**Comment by MathieuDoyon** [comment]
I'm getting it with https://github.com/vercel/next.js/tree/canary/examples/with-msw just by upgrading dependency to `"msw": "^0.42.1",`

**Comment by kettanaito** [comment]
In Next's case, the issue is that request listeners persist between HMR:

```sh
# This one listener is called multiple times.
[handlers] GET https://my.backend/book
[handlers] GET https://my.backend/book
[handlers] GET https://my.backend/book
# I've also changed the "console.log" to "console.trace"
# and you can see how the output above is from the previous HMR chunk.
Trace: [handlers] GET https://my.backend/book
    at eval (webpack-internal:///./mocks/handlers.js:10:17)
    at /contrib/with-msw-app/node_modules/msw/lib/index.js:569:54
    at RestHandler.run (/contrib/with-msw-app/node_modules/msw/lib/index.js:564:34)
    at /contrib/with-msw-app/node_modules/msw/lib/node/index.js:526:35
    at async getResponse (/contrib/with-msw-app/node_modules/msw/lib/node/index.js:521:18)
    at async exports.until (/contrib/with-msw-app/node_modules/@open-draft/until/lib/until.js:10:22)
    at async handleRequest (/contrib/with-msw-app/node_modules/msw/lib/node/index.js:1174:39)
    at async setupServerListener (/contrib/with-msw-app/node_modules/msw/lib/node/index.js:1256:25)
```

Since we are never disposing of the interceptor in Next, each HMR keeps appending a new listener from `setupServer` when re-evaluating the `mocks/server.js` code. We've had some HMR protection in place before but it looks like with the even-driven architecture we need to handle it explicitly once more.

**Comment by kettanaito** [comment]
I think I've found the root cause for this. We're using multiple interception strategies for Node.js (`ClientRequest` and `XMLHttpRequest`), and each of them appends its own "request" listener. This results in 2 total listeners being appended. Whenever a request is intercepted, it's piped through those listeners, but each listener is the same: it's the response lookup function from MSW. That lookup ends up being called twice, matches the request twice, and creates a race condition between whichever listener will respond the first (listeners are still identical). 

This looks like an issue with the `BatchInterceptor` class that composes multiple interceptors together. Looking into that.

**Comment by kettanaito** [comment]
I've opened a fix to tackle this issue in https://github.com/mswjs/interceptors/pull/262. 

The idea here is to somehow recover from hot module replacement. I've spotted that when it happens, the interceptors persist their "request" listeners. This is why a single request gets handled multiple times. What I'm doing as the initial fix is pruning any listeners that exist on child interceptors whenever a batch interceptor is constructed. I confirm that fixes this issue in the Next template. I suspect it will also fix it in other cases but haven't verified that yet. 

> _Edit:_ I've just noticed that the original reported repo also uses our Next template, so the fix above fixes it. 

Honestly, I don't know if this is the best approach to take. I'm not aware of an explicit API that'd allow us to react whenever HMR happens and perform some cleanup there. That would be ideal. I believe there was one with `module.hot.accept` in webpack but the ecosystem has migrated from it, and now using different means to live update code. 

If anybody knows of an API would could use here, please let me know. I'm thinking of something like this:

```js
// msw-internals.js
process.once('hotReload', () => {
  interceptor.dispose()
})
```

**Comment by kettanaito** [comment]
Does this happen for anybody _outside_ of Next? For example, during test runs in Jest? If so, please attach a repository so I could validate the fix. Thanks.

**Comment by kettanaito** [comment]
It's rather hard to construct a reliable test case for this. The issue happens because HMR re-evaluates some parts of the code but leaves the other parts stale. It re-evaluated the `new BatchInterceptor` call but left the created interceptor instances passed to its as arguments stale, preserving whatever listeners that may already have attached: 

https://github.com/mswjs/msw/blob/f37142d0cc9048f525792416d93e49f9f1d0786a/src/node/createSetupServer.ts#L63-L66

Perhaps this happened because `createSetupServer` accepts those interceptors as an argument. They are created in a different module, and since HMR is likely scoped to modules that can be affected by an update, it didn't bubble to where the interceptors are created:

https://github.com/mswjs/msw/blob/f37142d0cc9048f525792416d93e49f9f1d0786a/src/node/setupServer.ts#L10-L15

This behavior may change if we instantiate interceptors in `createSetupServer` function directly. I'm also curious whether there's any benefit of passing already created interceptor instances as opposed to passing interceptor classes to the batch interceptor and having it instantiate them instead. With the proposed fix above, you cannot append event listeners to child interceptors anyway—they will be pruned.

**Comment by kettanaito** [comment]
> This behavior may change if we instantiate interceptors in createSetupServer function directly.

This is the solution I'm going to go with. It's much cleaner than pruning `BatchInterceptor` children interceptor's events as proposed in https://github.com/mswjs/interceptors/pull/262.

**Comment by d-ivashchuk** [comment]
I was trying to get the correct responses in next js API routes and after [your suggestion here](https://twitter.com/kettanaito/status/1539375959773745155?s=20&t=n0YQ0H5qCiQfSJGleK0d_g) @kettanaito I am getting this `already responded` error being on the latest msw.

Here is a minimal repro with what I want to achieve as well!

https://github.com/d-ivashchuk/msw-next-api-routes

**Comment by kettanaito** [comment]
Thanks for letting me know, @d-ivashchuk. The fix for this hasn't been released yet, our overnight release job failed. Re-running that.

**Comment by kettanaito** [comment]
## Released: v0.42.2 🎉

This has been released in v0.42.2!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.42.2)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.42.2)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by d-ivashchuk** [comment]
oh, cool! I just check that fix has been merged to main but did not see the releases :D great job! thanks 🙌🏼

**Comment by M3kH** [comment]
This is so amazing thanks @kettanaito I was just setting up `msw` and facing this issue, you don't know how many cuddles I will like to give you since the solution was away from just upgrading the package.

Thank you so much for the hard work and for the great project!

**Comment by kettanaito** [comment]
Hey, my pleasure, @M3kH! I'm happy we were able to find a solution that's not entirely hacky. HMR is tricky, and it depends on the module evaluation, so certain modules are "preserved" while certain are re-evaluated. Funny how moving a class instantiation into a different module affects how that class will behave when under hot reload. If anything, the hot reload itself feels magical (perhaps too magical?). 

That being said, if you like my work and would like for MSW to grow and improve, please consider [sponsoring the project on GitHub](https://github.com/sponsors/mswjs). Let's build sustainable open source together, where features and bug fixes don't cost maintainer's personal lives and time.
