### ISSUE TITLE
Send the event data directly to and from the service worker without stringifying

### ISSUE THREAD

**Issue by 95th** [kettanaito/msw#1317]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Send the event data directly to and from the service worker without stringifying

**Comment by kettanaito** [comment]
This makes sense. I think stringification is there for historical reasons, from the early days of this library being a prototype. I've noticed that you can send objects (and even streams/buffers) over `BroadcastChannel` to the worker. That's what we've started doing since #1288, so I don't see a reason why we should still stringify request information in the `MessageChannel` between the worker and the client.

**Comment by kettanaito** [comment]
## Released: v0.44.0 🎉

This has been released in v0.44.0!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.44.0)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.44.0)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
