### ISSUE TITLE
MSW fails to resolve response on Safari

### ISSUE THREAD

**Issue by netcoding87** [kettanaito/msw#1324]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Safari

### Reproduction repository

https://github.com/netcoding87/msw-safari

### Reproduction steps

- `npm install`
- `npm run start`
- Open console in browser
- Click button "Fetch some data"
=> 'click' and the response object are logged, but not the result from `response.json()`

### Current behavior

The response object does not resolve the data in Safari. In other browsers (chromium, firefox) it is working... 

### Expected behavior

The response object resolves the data and the app can work with the responded data in Safari browsers

**Comment by mattcosta7** [comment]
I've seen the same behavior recently with msw version 0.43 and 0.44

**Comment by netcoding87** [comment]
> I've seen the same behavior recently with msw version 0.43 and 0.44

I can confirm this. Downgrading to msw `0.42.0` works...

**Comment by kettanaito** [comment]
On Safari, the worker request seems to be pending forever:

<img width="1388" alt="Screen Shot 2022-07-16 at 11 27 06" src="https://user-images.githubusercontent.com/14984911/179349117-a18d2a32-3c1d-4e54-a91c-963257f0344d.png">

You do get the `res` from fetch because it's created _while_ the response is in progress. 

In this regard, this issue looks similar to #1325, which mentions Firefox. Requests get resolved in Chrome, let me try Firefox. The exception is that in Firefox the request is stuck sometimes, and in Safari it gets stuck every time. 

Looks like we've introduced something in 0.43 that Safari doesn't like.

**Comment by kettanaito** [comment]
The main change in [0.43.0](https://github.com/mswjs/msw/releases/tag/v0.43.0) was the introduction of `ReadableStream` as the main mechanism to send the mocked response from the worker to the client. The worker now streams mocked responses to the client instead of sending them in a single chunk.

**Comment by kettanaito** [comment]
## Released: v0.44.2 🎉

This has been released in v0.44.2!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.44.2)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.44.2)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by mattcosta7** [comment]
New version looks good to me, thanks @kettanaito !
