### ISSUE TITLE
Allow runtime handlers to be persisted

### ISSUE THREAD

**Issue by Aaron-Pool** [kettanaito/msw#1345]
### Scope

Adds a new behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

For the sake of test performance, I like to be able to lazy load some of my mocking code. If I'm just working in a small area  and running a subset of tests, I often don't need a large portion of my mock code to be processed/run by the jest runner at all. However, if this means I have to repeatedly re-register a particular listener if several tests in a group _do_ use it, it introduces a set of drawbacks/overhead to this practice. 

I could always just _not_ call `resetHandlers` in the `afterEach` hook of jest. But then I have to take extra precautions if I ever _do_ want to add a single, test-specific runtime handler that I don't want to be persisted.

So, I'd like to suggest a new function be added to the `SetupServerApi`/`SetupWorkerApi`. I'm not sure what the name should be exactly, but something like `server.override`/`server.update`/`server.replace`/`server.persist` seem appropriate. I also think the `use` function returning an object with a `persist` method that moved the handlers from the temporary to the permanent list would be a pretty clean api, since `use` currently returns `void`. That way the user could do `server.use(...handlers).persist()` if they wanted to, which, like I detailed earlier, would cause the new handler(s) to be treated as if it were in the original batch of request handlers registered to the server when it was setup.

I've looked over the way handlers/server instances are managed (the node server api, at least), and it seems like it would be a pretty simple thing to add. I'd probably be up for doing the PR myself, I just didn't want to go through the hassle if the maintainer(s) here wouldn't approve of the API change.

**Comment by kettanaito** [comment]
Hey, @Aaron-Pool. Thanks for proposing this. 

While this looks like a practical feature, I don't think this is the direction we should take. I generally dislike any kind of implicitness (read "magic"), and a piece of logic persisting across modules (tests) is definitely an example of that. It will confuse more than it could help. Moreover, I believe that the current API is enough to cover close to any use case if used correctly. 

Your primary motivation here is performance, so allow me to elaborate on that. There's no performance degradation by attaching handlers via `.use()`. It really helps to see handlers split in a few groups during test runs:

1. General "happy path" handlers. Pass those to the `setupServer()` call always. They affect all tests.
2. Override handlers. Apply them via `.use()` in particular cases. Leverage [`res.once()`](https://mswjs.io/docs/api/response/once) when you need a more dynamic behavior. 
3. Always reset the handlers via `.resetHandlers()` so that any permanent overrides are cleared and don't persist across tests. 

Unless you have a collection of mocks that goes to a very big number, performance is a premature concern. If you do have such a large set of handlers, then it likely means your system is complex. Don't tackle complexity by introducing more complexity like `.persist()`. Instead, use other approaches. For starters, _split your tests_. If you feel like a long list of handlers degrades your tests' performance, then most of those handlers are irrelevant to a particular subset of tests, are they not? Create only a set of handlers that are relevant, and pass them to the `setupServer()` call (basically, split your "happy paths"). Each group of tests may instantiate its own "server" in that regard.

Also, note that you can pass a new list of handlers to `.resetHandlers()` that will replace the initial handlers (happy paths) passed to the `setupServer()` call. This behavior is documented [here](https://mswjs.io/docs/api/setup-server/reset-handlers#replacing-initial-handlers).

**Comment by Aaron-Pool** [comment]
@kettanaito sorry, I guess I wasn't clear about the performance degradation I was thinking about.

I was referring to the time it takes for jest to parse and transpile code, not the time it takes msw to match requests. If you're just debugging/fixing a single test, the execution time can suffer pretty significantly from having to bring in extraneous, unused code. Startup time has always been Jest's achilles heel, and that issue is exacerbated if the code brought in by your environment setup becomes significant.

**Comment by kettanaito** [comment]
I suppose in that case my "split test" suggestion still applies. I've been using MSW on projects of different sizes, and haven't noticed any issues while debugging Jest tests. Perhaps the issue may be on the setup you're using. Make sure your Jest environments, presets, and other extensions are up-to-date. We can't really solve performance issues for other tools.
