### ISSUE TITLE
can't handle request for shared workers

### ISSUE THREAD

**Issue by njoel24** [kettanaito/msw#1350]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

not available

### Reproduction steps

When trying to request a shared worker, the clientId attached to fetch event object is an empty string.

That causes the following line to break under mockServiceWorker.js in resolveMainClient function:
`if(client.frameType === 'top-level')`

I managed to make it work currently by checking for client like the following:
`if(client && client.frameType === 'top-level')`

With that I am able to work with shared worker.

Do you have any ideas why that happens?

msw version: 0.44.2

Thanks

### Current behavior

the msw fails handling the request

### Expected behavior

msw should handle the request.

**Comment by kettanaito** [comment]
Hey, @njoel24. 

Could you tell me more about your setup? It's really hard to advise anything without knowing what/how you're trying to do. 

This condition is a part of the `resolveMainClient` logic that tries to look up the actual client that has registered the worker. Since you may have nested clients (i.e. a page embed via `iframe`), we need to find the `top-level` client, which is always your application that called `worker.start()`. It's that client with which the worker must communicate, that client is responsible for request resolution. 

I don't have experience with shared workers. I'd be thankful if you contributed an integration test for that, which would reproduce the issue. Until then, I consider this issue closed for the lack of a reproduction scenario.

**Comment by njoel24** [comment]
Hey @kettanaito ,

thanks for your reply.

In the issue I described there are no iframes involved, it might be something related on how the shared worker requests the resource. 

Yes, I will definitely create an integration test for that, so you will have more details.

**Comment by njoel24** [comment]
hey @kettanaito ,


I created an integration test for the issue: https://github.com/njoel24/integration-test-ms-shared-worker
Just clone, install,  run 'npm run build' and run 'npm run start' and run the code on the browser.

Here what the error should be in console:

![test results](https://user-images.githubusercontent.com/71449544/181180386-74939054-1955-4640-8f7e-7e7df0f24e30.PNG)


Please note that the handler has not been implemented and left as null because the error happens before.

Kindly let me know if you need any more information.
I would  be more than happy to help.

**Comment by kettanaito** [comment]
## Released: v0.48.0 🎉

This has been released in v0.48.0!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.48.0)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.48.0)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
