### ISSUE TITLE
Doesn't intercept requests deeper in the scope of '/'

### ISSUE THREAD

**Issue by bogomazov** [kettanaito/msw#1366]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

- (sorry no repo to reproduce)

### Reproduction steps

`/mockServiceWorker.js` is in the root accessible from the browser
Using it for stories
```
import { setupWorker, rest } from "msw";

const mocks: any = [
  rest.post("/v2/user-management/users/get", null),
];

if (mocks.length > 0) {
  const worker = setupWorker(...mocks);
  worker.start({
    onUnhandledRequest: 'warn',
  });
  worker.printHandlers();
}
```

### Current behavior
<img width="522" alt="Screenshot 2022-08-19 at 14 11 00" src="https://user-images.githubusercontent.com/6625496/185616278-66b0caf6-897d-4484-919f-64d86e4c01bb.png">
<img width="518" alt="Screenshot 2022-08-19 at 14 10 13" src="https://user-images.githubusercontent.com/6625496/185616273-3cd1b60b-96f5-49c5-aa95-2674a165c3dc.png">

### Expected behavior

to show every unhandled request deeper then root path '/'

**Comment by bogomazov** [comment]
Maybe there is some quick gotcha that I am missing

**Comment by kettanaito** [comment]
Hey @bogomazov. Thanks for reporting this.

Based on the stack trace of those failed requests (`deferNetworkRequestUntil`), I can suspect that those requests fail before the worker is actually registered. We don't have any logic that'd route those request to `onUnhandledRequest` callback because the in-browser request handling relies on the worker. 

One thing we may try is to run deferred requests through the list of handlers during that stage. That should be okay in terms of executing the handlers once, as the request-handler-warning relationship remains 1:1. 

## Technical sidenote

This request behavior is really odd. Basically, the defer function ensures that no requests get executed until the worker is activated. So, the natural next step would be to:

1. Create a reproduction repository;
2. Debug if the worker is actually active by the time those requests fail (I suspect it's not).
3. Move from there.

If you have time to follow these steps, I'd be thankful. Otherwise, I can't dive into issues without a reproduction repository.
