### ISSUE TITLE
Make it more obvious when the serviceWorker.js doesn't match the msw version

### ISSUE THREAD

**Issue by jimmycallin** [kettanaito/msw#1382]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Hi! We recently upgraded msw which caused some issues related to the serviceWorker.js script not being up to date with what `msw init` generates. It wasn't immediately obvious for us exactly what caused this, and took some time to figure out that we needed to regenerate the worker.

We solved this by adding `msw init` as a step in `postInstall` in package.json, and adding the serviceWorker.js file to .gitignore. This way we can always be sure that we have the latest version of the worker. My proposal is that the documentation should be updated to have this as a recommended setup, to avoid this issue.

Furthermore I would also like to see msw track what version the serviceWorker.js was generated with, and output a warning about mismatching versions of msw and the generated serviceWorker.js file. I believe this would make it more obvious what our issue was.

Thanks!

**Comment by kettanaito** [comment]
Hey, @jimmycallin. Thanks for the proposal!

We have this behavior documented under the `init `command [options](https://mswjs.io/docs/cli/init#options). 

```sh
msw init ./path/to/public/dir --save
```

This command will save the path to the public dir in your `package.json`. MSW has a `postinstall` script, which will run whenever your project installs dependencies. That script checks if you have `packageJso.msw.workerDirectory` set and if you do it automatically generates the worker script in that path. 

Also, if you open your application in the browser with MSW enabled, you will see an error message describing that your worker is out of date. We do worker script integrity checksum validation every time MSW activates the worker. Was this error message missing during your testing? 

Overall, you've chosen the right approach to have an explicit `postinstall` on your side because we're going to deprecate our implicit `postinstall` eventually (see #1297).
