### ISSUE TITLE
Bypass main thread round trip for certain urls

### ISSUE THREAD

**Issue by jkieboom** [kettanaito/msw#1423]
### Scope

Adds a new behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

We are running our tests currently on AMD which means loading lots of javascript files. When the service worker is active, each single request requires a round trip to the main thread and back just to say that certain urls should `passthrough`. This adds significant latency in our case (test run time increases 3x in certain cases).

I did a quick proof of concept of having an exclude list of urls directly in the service worker so it can opt out of handling those urls entirely. This resolves the latency issue we're seeing.

It would be nice if there was functionality where we could configure the worker with such a list of url prefixes.

**Comment by kettanaito** [comment]
Hey, @jkieboom. Thanks for raising this. 

I understand the extra journey to the worker and back may have implications like latency but it's rather challenging to circumvent it entirely. When using MSW, the request flow is:

1. Request client dispatched a request;
2. Request hits the Network;
3. Request hits the "fetch" event of the worker;
4. The worker signals request info to the client;
5. The clients responds to the worker on what it should do with the request;
6. The worker proceeds with the request (either mocks it or bypasses it).

We cannot skip points 2 and 3 because the client won't be able to know anything about the request then. 

The whitelist of endpoints is data. The only way to pass the data to a worker is by posting a message. Posting a message is an asynchronous action, which means we introduce a window of uncertainty while it's being processed. In this light, even if we added something like

```js
worker.start({
  whitelistHosts: ['api.github.com']
})
```

we would have to send that whitelist data to the worker upon its start. To prevent intermittent behaviors, we'd have to await the worker to receive that data, which means a window during which no requests can be handled. Now, we have the same latency applied to every request anyway.

The most sensible way here is to compose workers, I think. You can have your custom worker that imports the MSW's worker via `importScripts()` but has some whitelisting logic built-in into itself that short-circuits the request processing before it hits the MSW worker. The issue with this is that you always end up with Request -> Worker -> Request journey no matter which context holds the whitelist data. It'd arguably have to be faster since there's no messaging back to the client, so you may give this a try. 

```js
// public/whitelistWorker.js
const whitelistHosts = ['api.github.com']

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url)

  if (whitelistHosts.includes(url.host)) {
    // I'd expect this early return to take precedence
    // over the MSW logic below, allowing you to
    // bypass it entirely, releasing the request.
    return
  }
})

importScripts('./mockServiceWorker.js')
```
