### ISSUE TITLE
@xmldom/xmldom@0.7.5 vulnerable to CVE-2022-37616 

### ISSUE THREAD

**Issue by leschdom** [kettanaito/msw#1432]
Hi! 
We got a warning in about a vulnerability in `@xmldom/xmldom`.
Updating to version `0.8.3` should fix it - see also https://github.com/xmldom/xmldom/security/advisories/GHSA-9pgh-qqpf-7wqj

```
npm ls @xmldom/xmldom
`-- msw@0.47.4
  `-- @mswjs/interceptors@0.17.5
    `-- @xmldom/xmldom@0.7.5
```

See https://github.com/mswjs/interceptors/blob/v0.17.5/package.json#L71

Thank you!

**Comment by kettanaito** [comment]
Hey, @leschdom. Thanks for reporting this. Please, would you like to open a pull request to the mswjs/interceptors repo?

**Comment by joshkel** [comment]
I started to submit a PR for this, but Dependabot beat me to it: https://github.com/mswjs/interceptors/pull/291

**Comment by kettanaito** [comment]
I've merged the dependabot's pull request. That should trigger the build and release, and since it's a patch version bump you will get it to your machines by re-installing `msw`.

**Comment by scottdickerson** [comment]
I don't see any new 0.47.5 release published and we would love to get this security fix.  Is there any way to manually kick a release?

**Comment by joshkel** [comment]
@scottdickerson , the fix was released as part of the @mswjs/interceptors package; msw itself wasn't affected.

Getting the new version of a transitive dependency like @mswjs/interceptors depends on your package manager. (For Yarn, I can manually edit yarn.lock, remove the `@mswjs/interceptors` block, then rerun `yarn`). Or it should work to uninstall (if needed) and reinstall `msw` (similar to what @kettanaito mentioned).

**Comment by kettanaito** [comment]
Or you can always use force installs as an alternative to manually editing the lock file. That should work with any manager.
