### ISSUE TITLE
Typescript 4.9 support

### ISSUE THREAD

**Issue by nnnnat** [kettanaito/msw#1462]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Update support matrix to include Typescript 4.9

**Comment by Kamahl19** [comment]
Why is this lib tight to specific minor version of TS anyway ? Why not any v4?

**Comment by kettanaito** [comment]
Hey, @nnnnat. Thanks for proposing this. 

We do plan to support newer versions of TypeScript. Once we do add support for 4.9, I'd advocate for dropping 4.2 and 4.3 so we keep a sensible matrix of supported versions. 

@Kamahl19, because TypeScript is not released according to semver. Each minor version of TypeScript may and likely does contain breaking changes. Thus, a more strict dependency range with an automated matrix of TS versions actually guarantees compatibility.

**Comment by sarimarton** [comment]
I understand the intentions of the authors that they want strict compatibility, but this causes more trouble than what it solves. I'm using up-to-date typescript in all of my projects and those are not compatible with msw. So I have 2 options: either add --force to the npm command (which is annoying) or override msw's peerDeps config from pnpm. The latter is feasible, but I still think that this cost is too high compared to the near-to-zero risk of any TS version mismatch issue a user might run into.
