### ISSUE TITLE
Cannot intercept a POST request (repository linked)

### ISSUE THREAD

**Issue by sineverba** [kettanaito/msw#1476]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v18.12.1

### Reproduction repository

https://github.com/sineverba/msw-issue

### Reproduction steps

npm install
npm run test

### Current behavior

```[MSW] Warning: captured a request without a matching request handler:
      
        • POST https://run.mocky.io/v3/2220b0ab-9a80-4d8d-831f-178e0b91f459
      
      If you still wish to intercept this unhandled request, please create a request handler for it.
      Read more: https://mswjs.io/docs/getting-started/mocks
```

### Expected behavior

POST call mocked / captured from msw

**Comment by sineverba** [comment]
I noticed that if I skipt test with `userEvent` library I don't have anymore the issue in console.


```js
// use skip
it.skip("Can press button", async () => {
    // Initialize user that interact
    const user = userEvent.setup();
    renderWithProviders(<LoginPage />);

    const inputUsername = screen.getByLabelText(/username/i);
    await user.type(inputUsername, "info@example.com");
    expect(inputUsername).toHaveValue("info@example.com");

    const inputPassword = screen.getByLabelText(/password/i);
    await user.type(inputPassword, "thisIsASecretPassword");
    expect(inputPassword).toHaveValue("thisIsASecretPassword");

    const loginButton = screen.getByRole("button", { name: /login/i });
    
    await user.click(loginButton);

    expect(localStorage.getItem(LOCALSTORAGE_ACCESS_TOKEN)).toEqual(accessToken)

  });
```

**Comment by kettanaito** [comment]
Hey, @sineverba.

You don't seem to be using the `.use()`/`.resetHandlers()` API correctly. This needs to be `beforeEach`:

https://github.com/sineverba/msw-issue/blob/8a13853d5cf088a6e4729649116739fedad49149/src/__tests__/views/LoginPage/LoginPage.test.js#L11

What happens in your current setup is this:

- `beforeAll` tests for the Login view you attach a runtime handler (`server.use()`).
- The first test runs but it has nothing to do with data fetching.
- The `server.resetHandlers()` triggers from the `afterEach` hook. _It removes the runtime handlers you've added in `beforeAll`_. This is what `.resetHandlers()` does by design. 
- The follow-up tests run, and by the moment it gets to the test concerned with data fetching, there are no handlers to for that request. 

So you can either:

1. Swap `beforeAll` with `beforeEach`.
2. Even better: call `server.use()` only in the tests that are concerned with data fetching. 

Also, consider not calling `server.close()` in a particular test where you haven't called `server.listen()` (you have `server.listen()` commented out so I don't know what the intention here).
