### ISSUE TITLE
Unable to get nested query params

### ISSUE THREAD

**Issue by harshsinghatz** [kettanaito/msw#1504]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

I am unable to get nested query params from req object 

I have used qs to stringify the query params. 

The query might look something like this
https://url/path?size=50&filter%5Btags%5D=all&filter%5Bquery%5D=293sdds93&filter%5Beta%5D%5Bstart_date%5D=&filter%5Beta%5D%5Bend_date%5D=&filter%5Betd%5D%5Bstart_date%5D=&filter

Problem is that i cannot access the complete URL with query params inside the handler

Is there a way to do this or this is something that not possible in msw

**Comment by harshsinghatz** [comment]
@kettanaito This would help alot

**Comment by mattcosta7** [comment]
@harshsinghatz you have full access to the request url and parameters inside a handler, so however you encode params you should be able to decode them.

A small sandbox shows parsing parameters however you like.  MSW doesn't prescribe how you encode/decode your parameters - it's up to you

https://codesandbox.io/s/msw-react-forked-vmwdii?file=/src/mocks/handlers.js

```js
rest.get("https://made.up/api/usage", (req, res, ctx) => {
    const url = new URL(req.url);
    // slice(1) to strip the `?` from the search
    const query = qs.parse(url.search.slice(1));

    return res(
      ctx.status(200),
      ctx.json({
        query
      })
    );
  })
```

If you have a specific example where you're struggling, happy to take a look - but since you can read urls from the request - you should be able to parse them however you like

**Comment by kettanaito** [comment]
@mattcosta7 is correct on this. 

- Full request URL is accessible via `req.url`.
- You can derive any necessary bits from the request URL, such as `new URL` or `new URLSearchParams()`, and also provide it to third-party libraries like `qs`.
- Since query parameter structure is your design, it's also you who should be deciphering it in the handler, need be.
