### ISSUE TITLE
ServiceWorker is not registered at the second test in Testcafe

### ISSUE THREAD

**Issue by Roy412** [kettanaito/msw#1508]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/Roy412/msw-testcafe-error/tree/msw_mock_issue

### Reproduction steps

- Clone the repository
- Install the packages - `yarn`
- Run the test - `yarn testcafe`

The second test fails because MSW service worker is not registered.
https://github.com/Roy412/msw-testcafe-error/blob/5ba82e4e7ce516caab9ad551691db83a0e5737d3/app/pages/_app.js#L18

<img width="865" alt="Screenshot 2022-12-27 at 10 22 24 AM" src="https://user-images.githubusercontent.com/34854380/209693559-d374ef0a-9fc7-41b4-b3a2-4592926e5b11.png">

### Current behavior

There're two tests that are exactly the same. The MSW service worker is registered successfully at the first test while it is not enabled for the second one. When there is only one test, it passes successfully and from the second test, it will fail.
On the second test, following code returns the multiple available `existingStates`.
https://github.com/mswjs/msw/blob/7380011de47460212065ca41be1b5a1c60ed1b98/src/setupWorker/start/utils/getWorkerByRegistration.ts#L17

<img width="757" alt="Screenshot 2022-12-27 at 12 28 22 PM" src="https://user-images.githubusercontent.com/34854380/209707922-a990f00a-457c-4110-a69d-3425303546ff.png">

And it returns the first one which was used at the first test. It should return the second one.

### Expected behavior

The MSW service worker should be registered correctly for the second test too.

**Comment by kettanaito** [comment]
That script URL looks broken to me. The worker should be registered at `http://localhost:64812/mockServiceWorker.js` _once_ to affect all the nested tests (notice that each test is served under a randomly generated path. Instead, it looks like each test serves its own worker, and registers it only under the test's path. 

Please refer to the TestCafe's docs to learn how to serve the worker script at the root of your test application. There has also been a ton of changes to MSW since this issue was filed, so please upgrade the library before trying anything else. Thanks.
