### ISSUE TITLE
ERR_NETWORK in Vitest when calling "vi.resetModules()"

### ISSUE THREAD

**Issue by breslauer** [kettanaito/msw#1529]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v16.18.1

### Reproduction repository

https://github.com/breslauer/msw-tests/

### Reproduction steps

```
yarn
yarn test:unit
```

**If you add request handlers to file `/src/tests/mocks/server` everything works**, but the problem is when you want to add mock as a part of test. 

File with test: https://github.com/breslauer/msw-tests/blob/main/src/components/__tests__/msw.spec.ts
Global config for msw: https://github.com/breslauer/msw-tests/blob/main/src/tests/mocks/server.ts - if u uncomment 5-9 lines, then everything works 

### Current behavior

You can't mock request, response is: 
```
Serialized Error: {
  "code": "ERR_NETWORK",
   ...
}
````

### Expected behavior

I can add mocked request hadnler as part of test, as is written in documentation: 
https://mswjs.io/docs/api/setup-server/use#runtime-request-handler

**Comment by jgarplind** [comment]
I ran into what seems like the same issue. In my case I followed up with another `it`-block and then the data would be returned as per the previous test's mocks.

Running `server.printHandlers()` reported that the appropriate handlers were attached at the time, but everything suggested some race condition where the handlers in fact weren't properly attached just yet.

I found what was for me a semi-satisfactory workaround, using a utility from @testing-library/react to `waitFor` a specific condition (indicating that the mock was applied, in my case:
```
await waitFor(() =>
      expect(result.current.data?.length).toBe(
        data.length - 1
      )
    );
)
```
to be fulfilled. Once past that check, later assertions would work as expected, indicating that the mock was now applied.

Hope this is useful either for resolving your particular problem or for delving deeper into the nature of the issue.

**Comment by willlymendoza** [comment]
@breslauer I've solved a similar issue by just moving the setup.js file from the /test folder to the root of the project leaving the file at the same level as the vite.config.(js/ts).

**Comment by kettanaito** [comment]
Hi, @breslauer. I've got some time to look into this and I think I found the problem.

## Root cause

The test fails and the request is not intercepted due to `vi.resetModules()` call in `src/test/setup.ts`. It looks like calling that forces Vitest to re-evaluate all imports in the test, making the `mockServer` you import in `setup.ts` and `mockServer` you import in `msw.spec.ts` to be _two different objects_. 

This means that the MSW server you start in the setup has no effect on the test.

## How to fix this?

Follow [Vitest's docs](https://vitest.dev/api/vi#vi-resetmodules) and put `vi.resetMocks()` in the `beforeEach()` test hook:

```diff
--- a/src/tests/setup.ts
+++ b/src/tests/setup.ts
@@ -1,8 +1,9 @@
-import { afterAll, afterEach, beforeAll, vi } from 'vitest'
+import { afterAll, afterEach, beforeAll, beforeEach, vi } from 'vitest'
 import server from './mocks/server'
 
 beforeAll(() => server.listen())
 afterAll(() => server.close())
+beforeEach(() => {
+  vi.resetModules()
+})
 afterEach(() => server.resetHandlers())
-
-vi.resetModules()
```

With this change, you still get the mocked modules reset before each test but the imports are no longer re-evaluated between the setup and the individual test files. You can see the test passing:

```sh
 ✓ components/__tests__/msw.spec.ts (1)

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  10:25:20
   Duration  940ms (transform 303ms, setup 77ms, collect 28ms, tests 38ms)
```
