### ISSUE TITLE
Allow status codes other than [200, 599]

### ISSUE THREAD

**Issue by sijakret** [kettanaito/msw#1552]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Returning status codes not in the range [200,599] currently produces an exception

```js
res(ctx.status(904, 'custom error code'));
```
_RangeError: Failed to construct 'Response': The status provided (901) is outside the range [200, 599]_

I have a scenario where I need to mock custom codes not in that range. If I understand, at least the mozilla docs, correctly this is not out of spec but custom behavior that is possible. https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#information_responses

> Note: If you receive a response that is not in [this list](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#information_responses), it is a non-standard response, possibly custom to the server's software.

Is there a reason to deliberately NOT allow other status codes?
What about mocking services that use custom codes?
Shouldn't there at least be an option to opt out of the checks for the [200, 599] range?

**Comment by kettanaito** [comment]
Hey, @sijakret. 

That limitation comes from the Fetch API specification that all browsers implement. MSW constructs a Fetch API `Response` to represent your mocked response, and that construct doesn't support response status codes outside of the 200 - 5xx range. While custom values outside of that range may be allowed per HTTP spec, they are not per Fetch API spec, which is what we are all using in the browser. 

> If init["[status](https://fetch.spec.whatwg.org/#dom-responseinit-status)"] is not in the range 200 to 599, inclusive, then [throw](https://webidl.spec.whatwg.org/#dfn-throw) a [RangeError](https://webidl.spec.whatwg.org/#exceptiondef-rangeerror).
> —[Source](https://fetch.spec.whatwg.org/#response-class)

I acknowledge it's a bit confusing since the very same spec mentions:

> A status is an integer in the range 0 to 999, inclusive.
> —[Source](https://fetch.spec.whatwg.org/#concept-status)

But that is not how response _constructor_ works.

I understand your intention to construct a custom response from a server in this regard but that's the platform limitation we have to deal with. I recommend you use 5xx codes to represent your logic. To my best knowledge, 5xx response status codes are arbitrary status codes you can use for your current use case.

**Comment by kettanaito** [comment]
You can raise this question to the W3C/HTML committee to get a more insightful answer as to why `ResponseInit.status` is limited to `[200, 599]` range.

**Comment by sijakret** [comment]
Thanks a lot for the clarification!
I guess i need to try to persuade the backend people to move to 5xx :)
