### ISSUE TITLE
ReferenceError: location is not defined in Node.js

### ISSUE THREAD

**Issue by till** [kettanaito/msw#1555]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

18.14.2

### Reproduction repository

https://github.com/till/msw-location-error

### Reproduction steps

```
npm install
./node_modules/.bin/vitest
```

### Current behavior

```
 FAIL  tests/request.test.js > request
ReferenceError: location is not defined
 ❯ FetchInterceptor.<anonymous> node_modules/@mswjs/interceptors/src/interceptors/fetch/index.ts:50:22
 ❯ step node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:59:23
 ❯ Object.next node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:40:53
 ❯ fulfilled node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:31:58
```

### Expected behavior

I can mock the request

**Comment by kettanaito** [comment]
Hey, @till. Thanks for reporting this. 

Looks like our fetch interceptor relies on `location` a bit too optimistically. Since we now allow for this interceptor to be used in Node.js, we need to account for the location not being present (it never is unless you're running DOM-like environment patch in Node.js). 

The fix itself should be to check the existence of `location` before accessing it right here:

https://github.com/mswjs/interceptors/blob/407d3e4de4968bea22817dd0def0ce09f1c98005/src/interceptors/fetch/index.ts#L50

Also worth mentioning that the version of Interceptors MSW runs on right now is the _old_ version (0.17.7), so I need do issue a patch to that old version. The latest version doesn't seem to depend on `location` in any way but we will get that only with the Fetch API support.

**Comment by till** [comment]
I can try to upgrade it? 🥳

**Comment by kettanaito** [comment]
@till, that would be awesome! Are you comfortable with branching changes from a specific moment of Git history? As I've mentioned, the line we have to fix is not in the latest state of the Interceptors repo. It's nothing too complex though:

1. Clone the `@mswjs/interceptors` repo.
2. Checkout the latest tag we need to fix: `git checkout chore/0.17.7`
4. Create a new branch: `git checkout -b fix/fetch-location`
5. Implement the fix.
6. Open a pull request from `fix/fetch-location` to `chore/0.17.7`

I think you need my help with `chore/0.17.7` to open a PR to that branch on the original repo and not on your fork. 

_Edit:_ I've pushed `chore/0.17.7` to the origin so you should be able to go from there and open a pull request to that intermediate branch.

**Comment by till** [comment]
I made a PR on the interceptor, but I am not entirely sure if that's the best fix (not really good with JavaScript or TypeScript), but also found a work around if you are mocking one thing:

```js
test('foo', async () => {
  global.location = new URL('something/I/wanna/mock')
  const resp = await fetch('something/I/wanna/mock')
})

**Comment by joshkel** [comment]
I've run into a possibly related issue: When running in Jest, Jest shuts down its jsdom environment as part of test cleanup, so an in-progress mocked `fetch` request may access `location` and fail (even with [the recent fix](https://github.com/mswjs/interceptors/commit/3bbcd16d6b4a83c8ea94210886374aa7b49ec7d3), because jsdom's `location` uses a [getter](https://github.com/jsdom/jsdom/blob/65ef06f3771a33dcbf7bef442fdc7e07816d008d/lib/jsdom/browser/Window.js#L391) that won't work after Jest shuts it down).

See https://github.com/vercel/swr/issues/2463.

I'm not sure if this is MSW's responsibility to fix, and (as you said) it looks like it won't be an issue in later versions of @mswjs/interceptors, but I wanted to mention it in case it's relevant or in case anyone else runs across it.

**Comment by kettanaito** [comment]
@joshkel, this has been fixed by @till and is published already. Re-install your dependencies and you will get the fix automatically. To verify:

```
npm ls @mswjs/interceptors
```

Should print `0.17.8`.

**Comment by till** [comment]
@kettanaito Ah, had no idea. Thanks!

Do I just update (`npm install`) the interceptor? I don't want to blanket delete lock etc.?

**Comment by kettanaito** [comment]
@till, just run `npm install`. Your package manager should pull the latest dependencies that match the range. I've posted the command to verify that it worked as expected https://github.com/mswjs/msw/issues/1555#issuecomment-1447957959

**Comment by wladpaiva** [comment]
I ran into this issue and could not solve it on pnpm only by running the install again. It did not update the pnpm-lock so I had to override the `msw>@mswjs/interceptors ` to the latest version, installed and then removed the override and it installed again, the correct version this time. Don't ask me why ¯\_(ツ)_/¯

**Comment by kristojorg** [comment]
FYI I had to manually `npm update @mswjs/interceptors` in order to get the new version

**Comment by virtuoushub** [comment]
> I've run into a possibly related issue: When running in Jest, Jest shuts down its jsdom environment as part of test cleanup, so an in-progress mocked `fetch` request may access `location` and fail (even with [the recent fix](https://github.com/mswjs/interceptors/commit/3bbcd16d6b4a83c8ea94210886374aa7b49ec7d3), because jsdom's `location` uses a [getter](https://github.com/jsdom/jsdom/blob/65ef06f3771a33dcbf7bef442fdc7e07816d008d/lib/jsdom/browser/Window.js#L391) that won't work after Jest shuts it down).
> 
> See [vercel/swr#2463](https://github.com/vercel/swr/issues/2463).
> 
> I'm not sure if this is MSW's responsibility to fix, and (as you said) it looks like it won't be an issue in later versions of @mswjs/interceptors, but I wanted to mention it in case it's relevant or in case anyone else runs across it.

I am also running into this, and finding it hard to create a consistent reproduction case; as it works locally, but fails in GitHub actions, CI/CD land.

I can confirm I am on `0.17.9`:

```sh
yarn why @mswjs/interceptors
├─ msw@npm:1.2.1
│  └─ @mswjs/interceptors@npm:0.17.9 (via npm:^0.17.5)
│
└─ msw@npm:1.2.1 [d16b5]
   └─ @mswjs/interceptors@npm:0.17.9 (via npm:^0.17.5)
```

error observed:

```log
2023-04-28T20:16:00.4884197Z TypeError: Cannot read properties of null (reading '_location')
2023-04-28T20:16:00.4885320Z     at Window.get location [as location] (/home/runner/work/foo-bar/foo-bar/node_modules/jsdom/lib/jsdom/browser/Window.js:376:79)
2023-04-28T20:16:00.4886171Z     at FetchInterceptor.<anonymous> (/home/runner/work/foo-bar/foo-bar/node_modules/@mswjs/interceptors/src/interceptors/fetch/index.ts:50:22)
2023-04-28T20:16:00.4887156Z     at step (/home/runner/work/foo-bar/foo-bar/node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:59:23)
2023-04-28T20:16:00.4887959Z     at Object.next (/home/runner/work/foo-bar/foo-bar/node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:40:53)
2023-04-28T20:16:00.4888916Z     at fulfilled (/home/runner/work/foo-bar/foo-bar/node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:31:58)
2023-04-28T20:16:00.4889408Z     at runNextTicks (node:internal/process/task_queues:60:5)
2023-04-28T20:16:00.4889800Z     at processImmediate (node:internal/timers:447:9)
```

---

unfortunately upgrading to the latest `@mswjs/interceptors` does not work. Happy to create a new issue if one does not already exist, as I think this case is slightly different than the original #1555 one.

**Comment by jfstn** [comment]
I was facing the exact same issue today @virtuoushub . 

Needed to revert back to `1.0.0` to avoid the need to rewrite a bunch of tests.

This is the error I was getting: 
```
ReferenceError: location is not defined
    at FetchInterceptor.<anonymous> (*/node_modules/@mswjs/interceptors/src/interceptors/fetch/index.ts:50:22)
    at step (*/node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:59:23)
    at Object.next (*/node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:40:53)
    at fulfilled (*/node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:31:58)
```

We might need to create that issue as it seems that the problem persists even with the interceptor at `0.17.8`.

**Comment by kettanaito** [comment]
This is quite a pickle. The published code for `@mswjs/interceptors@0.17` accesses the `location` object only if it exists:

https://github.com/mswjs/interceptors/blob/ca47c880790cabab58e667d1a81a82d25ab31a33/src/interceptors/fetch/index.ts#L51-L54

This was originally the fix for this issue. Could someone please open the code for `node_modules/@mswjs/interceptors` and its `FetchInterceptor` to see how the `location` is accessed?

If there's still a safeguard like above, which I believe there will be if you're using the latest `0.17.x`, then it seems that the test environment itself defines the global `location` object but fails to access it. Are you by any chance using Jest?

**Comment by ssl37** [comment]
> If there's still a safeguard like above, which I believe there will be if you're using the latest `0.17.x`, then it seems that the test environment itself defines the global `location` object but fails to access it. Are you by any chance using Jest?

@kettanaito The issue is that jsdom sets a getter for location that depends on window._document, and that variable is null after the window.close() is called. Hence the reason for the typeerror can't read _location of null. [See the jsdom code](https://github.com/jsdom/jsdom/blob/a39e0ec4ce9a8806692d986a7ed0cd565ec7498a/lib/jsdom/browser/Window.js#L391-L393).

I've 'patched' my local copy of src/interceptors/fetch/index.ts at line 53 with 
`        document && typeof location !== 'undefined' ? location.origin : undefined`
and it works to avoid the errors: document is the getter for window._document, and so it safeguards the call to the location getter by short circuiting if document isn't defined.

**Comment by kettanaito** [comment]
Thanks for looking into it, @ssl37! I don't think that's the right way to solve it on the library's side though. That `document`/`location` relationship is entirely specific to JSDOM, and we don't ship library-specific workarounds. If anything, this sounds like an issue in JSDOM to me. If the `location` object is accessible, the code should be able to read it. `window.close()` shouldn't even be called in the JSDOM environment, this makes very little sense to me. 

Do you happen to know what triggers `window.close()`, causing this issue?

**Comment by ssl37** [comment]
I do not know for sure, it seems like `window.close()` is called by jest
when it cleans up tests.

This problem is an artifact of how msw is being used while running tests.
[joshkel summarized the problem in this comment](
https://github.com/mswjs/msw/issues/1555#issuecomment-1447188239): JSDom
has cleaned up after tests, and then later the fetch interceptor attempts
to run, causing an error. If you think this is library-specific, that is
fine, you don't need to provide a workaround. I was merely describing why
the `typeof location !== undefined` was not guarding against the error some
of us are seeing.

It would be nice to be able to cancel any pending fetch handlers at the
same time as a call to `server.resetHandlers()`, though I don't know how
practical it is.
