### ISSUE TITLE
Very different behavior with create-react-app between v1.0.1 and v1.1.0

### ISSUE THREAD

**Issue by Lukas-Kullmann** [kettanaito/msw#1557]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v18.14.0

### Reproduction repository

https://github.com/Lukas-Kullmann/msw-cra-issue/

### Reproduction steps

The behavior of msw changed quite a lot in our create react app project between versions v1.0.1 and v1.1.0.

In some places, we use `res.networkError('...')` in quite some places. In msw v1.0.1, a call to `fetch()` would result in a `TypeError` (that comes from whatwg-fetch). In v1.1.0, it throws a `NetworkError` (that comes from msw).

Why did the behavior change so drastically between these versions without a major release?

### Current behavior

```typescript
// setup
rest.get("https://examle.com/fails", (request, response) => {
  return response.networkError("oh no!");
})

fetch("https://examle.com/fails")
```

The fetch call rejects with a NetworkError in msw v1.1.0, but with a TypeError in msw v1.0.1.

Please refer to the test file in the reproduction repo that contains the whole process: https://github.com/Lukas-Kullmann/msw-cra-issue/blob/4ac10a3/src/msw.test.js

### Expected behavior

The fetch call rejects with the same error, regardless of v1.0.1 or v1.1.0.

**Comment by kettanaito** [comment]
Hi, @Lukas-Kullmann. Thanks for reporting this. 

We haven't shipped anything aimed directly at the behavior you're experiencing. My suspicion goes to the added support of global `fetch` in Node.js since 1.1.0. This is how `fetch` worked previously (on older versions of Node):

- fetch()
  - your polyfill of choice, 99% relying on http.ClientRequest
    - MSW: handle intended exception from ".networkError()"

How it works with the global `fetch` support:

- fetch()
  - MSW: intercept and mock responses.

We will be skipping any underlying polyfills for `fetch` in 1.1.0 _if there's a global fetch present_. I assume that's precisely how you're using whatwg-fetch. 

Why are you using whatwg-fetch if you're on Node.js v18? Have you tried your reproduction scenario without the polyfill? Node 17+ supports global fetch, and I wonder what the difference in the behavior will be if you use that instead. 

That may be an MSW issue in the end. I don't know from the top of my head how network errors will surface in fetch's context but bear in mind that fetch doesn't usually tolerate custom errors. This is true for whatwg-fetch as well, I believe. Anything throwing as a part of request/response resolution becomes `TypeError`, which is an implementation detail of whichever fetch implementation you're using. This is different if compared to throwing errors on the `http.ClientRequest` level as we're lower in the request processing chain. That being said, any error bubbles up and gets handled by the fetch implementation so I'm not certain to jump to conclusions here.

**Comment by kettanaito** [comment]
Implementation-wise, the difference is that previously we handled resolver exceptions in a special way in `http.ClientRequest`:

https://github.com/mswjs/interceptors/blob/beb1561770403e6175e24e7948da53418cf50ddc/src/interceptors/ClientRequest/NodeClientRequest.ts#L194-L204

While now, we don't have any exception handling on the fetch interceptor side at all:

https://github.com/mswjs/interceptors/blob/beb1561770403e6175e24e7948da53418cf50ddc/src/interceptors/fetch/index.ts#L53

I'm not aware of how to properly emulate a network error on the fetch's level. This needs some additional research. My naive assumption here is to:

1. Catch the exception.
2. Abort the pending request (or forward that exception to the pending request somehow).
3. Throw that exception as-is so you get `NetworkError` instance.

**Comment by Lukas-Kullmann** [comment]
Thanks for your reply, @kettanaito !

> Why are you using whatwg-fetch if you're on Node.js v18? Have you tried your reproduction scenario without the polyfill? Node 17+ supports global fetch, and I wonder what the difference in the behavior will be if you use that instead.

`create-react-app` automatically applies the polyfill if needed. In the default settings, it is needed since we are using the jsdom environment in jest and jsdom does not provide a fetch interface. 
That is why we cannot just not use the polyfill. We would have to overwrite the testing environment.

> Anything throwing as a part of request/response resolution becomes TypeError, which is an implementation detail of whichever fetch implementation you're using.

I don't really think so. At least according to mdn, this should be a TypeError: https://developer.mozilla.org/en-US/docs/Web/API/fetch#exceptions

> [TypeError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError)
>    Can occur for the following reasons:
> ...
> If fetch throws a network error.

**Comment by kettanaito** [comment]
So what you're stating means that the 1.1.0 behavior is actually correct? If per MDN fetch should throw a TypError upon a network error, and what you're saying:

> The fetch call rejects with a NetworkError in msw v1.1.0, but with a TypeError in msw v1.0.1.

Then we're indeed throwing a TypeError since 1.1.0. Is that correct?

**Comment by Lukas-Kullmann** [comment]
No, the behavior in 1.1.0 is actually wrong. 
It should throw a `TypeError`, but it does not. It throws a `NetworkError`.

**Comment by kettanaito** [comment]
I've implemented a fix for it in https://github.com/mswjs/interceptors/pull/356. @Lukas-Kullmann, may I kindly ask for your review on it?

**Comment by Lukas-Kullmann** [comment]
Thank you for the swift fix!

It looks good, but I don't know how I can test it. I tried just linking the version of your PR into my example repo, but the versions seem to be too far apart for this to work (i.e. the version of your branch has a vastly different folder structure in the `lib` directory than in the version that is used in msw at the moment). I get an error `Cannot find module '@mswjs/interceptors/lib/utils/bufferUtils.js' from 'node_modules/msw/lib/index.js'` which is true. There is no `utils` folder in the `lib` folder. It just has `browser` and `node`. I guess I would need to use some kind of experimental version of msw, too. But I don't know which.

**Comment by kettanaito** [comment]
That's such a good reminder, thanks. I need to backport this fix to 0.17.x as well as it would propagate to MSW. The newer versions are indeed incompatible and are not used in MSW. We're migrating to them as a part of the Fetch API support.

**Comment by kettanaito** [comment]
I'm backporting the fix to 0.17 in here https://github.com/mswjs/interceptors/pull/357

@Lukas-Kullmann, may I kindly as you to test the linked changes in your app? They are 0.17-compatible.

**Comment by Lukas-Kullmann** [comment]
Yes, that works now, thank you so much!

**Comment by kettanaito** [comment]
Awesome! Released in `@mswjs/interceptors@0.17.9`. Thanks for reporting this.

**Comment by loughlinclaus3** [comment]
Instead of using `console.error` [here](https://github.com/mswjs/interceptors/commit/287247d96a452986790a216b2dd404de5182438b#diff-4593f50c24857397e849d8d6618757914a847fa2642a22bfaa3b703e15cb4969R91), should it instead be using `this.log`, as it does elsewhere in the file?

When I intend to test a network error using the [`res.networkError()`](https://mswjs.io/docs/api/response/network-error), it's logging an error message in the middle of my jest test cases when it didn't before.

**Comment by kettanaito** [comment]
@loughlinclaus3, I don't think so. When a network error happens, you see two things:

- A console error of `net::ERR_FAILED`
- A promise rejection error.

And those are not the same things. It's hard to reason about the previous functionality because the global fetch support is new, so there was no previous functionality in this regard.

**Comment by loughlinclaus3** [comment]
That is usually true, with the exception of scenarios where a fetch() is followed by a .catch(e => {....}), in which case, the console.error is not executed, and instead whatever is in the body of the catch runs.

Though, on second thought, it probably shouldn't be a console.log either, as that would still fire even with a catch.
