### ISSUE TITLE
msw@0.0.0-fetch.rc-6: SSE POST endpoint with and Node 19 hangs jest

### ISSUE THREAD

**Issue by acdcjunior** [kettanaito/msw#1562]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

19.7.0

### Reproduction repository

https://github.com/acdcjunior/msw-sse-jest-hangs

### Reproduction steps

- clone the https://github.com/acdcjunior/msw-sse-jest-hangs repo
- make sure you are using a Node 19 (e.g. 19.7.0)
- `yarn`
- `yarn test`

### Current behavior

You will notice that the process never finishes.

### Expected behavior

If you switch to Node 18 it does finish, as expected.

**Comment by acdcjunior** [comment]
Just to clarify, for the SSE endpoint, I'm using the example here: https://github.com/mswjs/msw/blob/feat/standard-api/MIGRATING.md#support-readablestream-mocked-responses

Also, I realize Node v19 may not be in the list of supported versions for now (I did search for it but the [closest thing](https://github.com/mswjs/interceptors/issues/217) I could find is this), so please feel free (of course) to disregard the issue. I'm just reporting it because I spent some time tracking down the cause and maybe something good comes out of it.

FWIW, on our end, we're "fixing" it by switching back to Node18 for now.

**Comment by kettanaito** [comment]
Hey, @acdcjunior. Thanks for reporting this. 

We haven't conducted any testing on Node 19 since we test everything on Node 18. It may as well be a bug in Node, those happen. To differentiate, could you try your use case on Node 20? Odd versions of Node are generally considered unstable so I doubt MSW will provide any official support for them or look into issues happening on those versions. Thanks for understanding. 

Also don't forget to update the release candidate version since at the moment of writing this the latest version is `0.0.0-fetch.rc-15` (always do `npm i msw@next`). Thanks!
