### ISSUE TITLE
Msw is not working with NextJS app directory

### ISSUE THREAD

**Issue by mcAnastasiou** [kettanaito/msw#1565]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Previously the msw was working perfectly with NextJS. NextJS introduced a new structure called app directory. It seems that requests made on server side components are not intercepted by msw anymore. Could you fix this or propose a solution to this?

**Comment by kettanaito** [comment]
Hi, @mcAnastasiou. Thanks for raising this. 

There is no official way to use MSW with the new NextJS 13, which is still in beta. We've raised this discussion with the Next team, as they've removed the logic that'd allow executing code _once_ for server/client with their new directory structure. That's the main challenge to make MSW work with it at the moment. 

You can follow the progress in the mentioned issue: https://github.com/vercel/next.js/issues/43284#issuecomment-1339929638

I will close this one because it's not a problem with MSW. It's a problem of missing proper integration point on the Next's side.
