### ISSUE TITLE
 NextJS - Cannot read properties of undefined (reading 'listen')

### ISSUE THREAD

**Issue by AtomSpy** [kettanaito/msw#1574]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v18.13.0

### Reproduction repository

https://github.com/kevinstark86/smiley

### Reproduction steps

npm install
npm run dev

### Current behavior

Unable to call the correct msw setup using `server.listen()` or `worker.start()`

![Screenshot 2023-03-22 at 20 55 01](https://user-images.githubusercontent.com/56278539/227035839-2e2f562b-c5bd-49ea-b113-35f0da5b7d44.png)

Throws an error saying "TypeError: Cannot read properties of undefined (reading 'listen')

![Screenshot 2023-03-22 at 20 55 40](https://user-images.githubusercontent.com/56278539/227035982-6ca28f70-bf63-4fc9-9bc5-f01f16016a64.png)

I have followed issue #1227 which suggests that something is forcing the modules to be important asynchronously. The solution given in issue #1227 was to async await import `server` and `worker`. However, this has not resolved the problem.

### Expected behavior

I expect the correct MSW setup to be called.

**Comment by kettanaito** [comment]
Hi, @kevinstark86. Thanks for reporting this. 

It looks like there's no exported property `server` from the `./server` module. Can you show me what's the content of that module? 

It also seems that the Next.js team recommends using `import` since `require` statements won't be tree-shaken and MSW will, inevitably, end up in your production bundle even if you enable it conditionally. Please try switching to `await import('./server')`, that has to help. 

If it doesn't, inspect the exported object from those modules and see what may be wrong:

```js
const obj = await import('./server')
console.log(obj) // what keys are here? 
```

**Comment by kettanaito** [comment]
Also, if encountering issues with Next 13, please follow #1644 where we track the progress of supporting the App directory. Thanks.
