### ISSUE TITLE
Use latest version of `@msw/interceptors` in the msw package

### ISSUE THREAD

**Issue by trevoro** [kettanaito/msw#1579]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

I was stumbling around trying to figure out why msw was failing after upgrading MSW using Node v18.
It turns out that all I had to do was install `@msw/interceptors@latest` and everything works just fine.

Prior to that we were always getting an error about the location not being found, so something wasn't being intercepted correctly. 

I suspect that the dependency of `@msw/interceptors` should be bumped.

**Comment by danny-does-stuff** [comment]
The issue with this change is that then msw will lose support for node <v18. I think this is probably very closely related to #1464 which may solve your issue when it's released

**Comment by trevoro** [comment]
Well that's fine but you need to make a decision on when you want to split
the support.
If this new version isn't backwards compatible then it's probably time to
just release MSW version 2 where the only distinction is that node < 18
isn't supported.
Otherwise you're sort of hiding some important behaviour from users.

**Comment by kettanaito** [comment]
Hi, @trevoro. Thanks for raising this. 

The new versions of the Interceptors library already use the Fetch API primitives. This makes the current state of the library incompatible with the new Interceptors versions. We will (and already have) update to the new version of Interceptors as a part of #1436 in the nearest future. That will be available in `msw@2`. 

Regarding the Node.js support, `msw@1` still supports v14 - v17 range of Node.js. We never had support for Node.js 18 (see #1388) and are already working on that support in the mentioned Fetch API feature branch. It is with that `2.0` release that we will drop support for older versions of Node.js as well. 

I'm not planning on splitting this into multiple releases because I don't have the man-power to see all that through. The Fetch API initiative is as gigantic as it gets, and I'd rather direct my time and energy to wrapping it up.
