### ISSUE TITLE
MSW not working with node-fetch

### ISSUE THREAD

**Issue by hardikkaji** [kettanaito/msw#1581]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v18.13.0

### Reproduction repository

https://github.com/hardikkaji/node-fetch-msw-example

### Reproduction steps

1. Install dependencies using `npm i`
2. Run `npm run test`

### Current behavior

Test is failing due to timeout

![Screenshot 2023-04-03 at 09 10 09](https://user-images.githubusercontent.com/4531780/229447498-3dcb7a04-db18-4994-ba99-7102f1d48fd1.png)

### Expected behavior

Test should pass

**Comment by hardikkaji** [comment]
Update:

I have tried to downgrade my Node.js version to 17 --> issue still persists. (Test is failing)

With Node.js 16, Issue doesn't exist mean Test is passing.

**Comment by kettanaito** [comment]
Hi, @hardikkaji. Thanks for reporting this. MSW doesn't support Node.js 17/18 at the moment. We are almost done with that support in #1436 which is going to be released in the next major version. Sorry for the confusion, we are not setting an upper range on the supported `engines.node` because we have people using MSW in Node 18 without issues, which makes me believe it's use-case-dependent (locking the upper range means failed installations on unmatching Node versions). 

Please wait until the next major version is released. Thanks!
