### ISSUE TITLE
Add option to format generated worker file

### ISSUE THREAD

**Issue by robertjk** [kettanaito/msw#1595]
### Scope

Adds a new behavior

### Feature description

It would be nice to add option of running formatting command on generated worker file (e.g. `public/mockServiceWorker.js`).

In our project all JS files are formatted using Prettier to ensure consistent formatting across all source code we have in repo and might be reading. Our `mockServiceWorker.js` is as well. With this setup every time a new `mockServiceWorker.js` is generated (and that happens quite often, every time a package is installed or upgraded) is unformatted and shows as a whole changed file in version control system. That requires running Prettier on it manually, which quickly gets annoying.

I am aware it's possible to turn off Prettier on that file (and that's probably what we'll do for now), but it'd also be nice to add option of formatting any generated files, so that they match whatever project's formatting standards.

**Comment by kettanaito** [comment]
Hey, @robertjk. Thanks for raising this. 

The official stance on this is that you should treat the worker script as a build artifact (similar to the `*.js` files emitted by your bundler). With that in mind, you don't have to format or lint the worker script. Your Prettier shouldn't affect files in `/public` anyway (the same goes for linting tools). 

If you absolutely want to keep the worker script formatted, you can set up a custom script in package.json and run it whenever you generate a new worker.

```json
{
  "scripts": {
    "msw:init": "npx msw init ./public && prettier ./public/mockServiceWorker.js -w"
  }
}
```

> You may want to consult Prettier on the correct CLI usage, my memory may be rusty. 

But I will emphasize that you don't gain any benefits from this so you are better off omitting any linting/formatting of the build assets. 

> With this setup every time a new mockServiceWorker.js is generated (and that happens quite often, every time a package is installed or upgraded)

I suppose you're referring to `msw.workerDirectory` being kept in your package.json? So that any `msw` installation re-triggers the copying of the worker script. That's actually something we can improve, I think. At least, we can check the existing script, extract its version, and compare it with the installed one. If they match, we may skip the copying altogether.

**Comment by robertjk** [comment]
@kettanaito Thanks for the detailed explanation. It sounds very reasonable. You convinced me that's what we should do - disable `public/` from being formatted by Prettier.
