### ISSUE TITLE
Can't combine a log handler and `onUnhandledRequest`

### ISSUE THREAD

**Issue by florian-milky** [kettanaito/msw#1602]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v18.12.1

### Reproduction repository

https://github.com/mswjs/examples/tree/master/examples

### Reproduction steps

Define a `rest.all` that doesn't return anything and `onUnhandledRequest` to `error` (for example).
Trigger a request.

### Current behavior

Getting message:
```
[MSW] Expected response resolver to return a mocked response Object, but got undefined. The original response is going to be used instead.
```

`onUnhandledRequest` is ignored

### Expected behavior

No getting the current message and triggering the `onUnhandledRequest` property

**Comment by kettanaito** [comment]
Hi, @florian-milky. Thanks for raising this.

Are you returning `req.passthrough()` ([docs](https://mswjs.io/docs/api/request/passthrough)) from your resolver?

MSW used to tolerate undefined returns but we've moved away from it a couple of versions ago since it's impossible to distinguish between an explicit intention to bypass a request and a mistake of forgetting to return a mocked response.

**Comment by florian-milky** [comment]
Hi @kettanaito, 

> Are you returning req.passthrough() ([docs](https://mswjs.io/docs/api/request/passthrough)) from your resolver?

At first I did, but then the request is not passed to the other handlers.

> MSW used to tolerate undefined returns but we've moved away from it a couple of versions ago since it's impossible to distinguish between an explicit intention to bypass a request and a mistake of forgetting to return a mocked response.

So having "middleware"-style handlers is not supported then? A request should only be handled by one handler and no more?

Basically what I'm missing is a little bit more fined grained control over logs. I'd like to log requests that are handled as well, not just requests that are not handled.

**Comment by kettanaito** [comment]
> At first I did, but then the request is not passed to the other handlers.

Yes, this is how the passthrough works: it instructs _to perform the request_, ignoring any other otherwise matching handlers. 

> A request should only be handled by one handler and no more?

This is not true. The captured request goes through the list of relevant handlers and the first returning response is used. That's the intention, at least. 

I think you're making a great point that it's not that accessible to build middleware-style handlers. What kind of API do you see in mind for us to support this? 

> Basically what I'm missing is a little bit more fined grained control over logs. I'd like to log requests that are handled as well, not just requests that are not handled.

Then you're using the API wrong. Request handlers are responsible for resolving requests but what you want to do is to perform side-effects when a request/response happens. We have the [Life cycle API](https://mswjs.io/docs/extensions/life-cycle-events) specifically designed for this purpose.

Here's an example of how you can use the mentioned API to log requests, regardless of whether they are mocked/bypassed:

```js
server.events.on('request:start', (request) => {
  mgLogs.addEntry(request.method, request.url)
})
```

**Comment by florian-milky** [comment]
> Then you're using the API wrong. Request handlers are responsible for resolving requests but what you want to do is to perform side-effects when a request/response happens. We have the [Life cycle API](https://mswjs.io/docs/extensions/life-cycle-events) specifically designed for this purpose.

This is awesome! Exactly what I need. Thank you so much!

> I think you're making a great point that it's not that accessible to build middleware-style handlers. What kind of API do you see in mind for us to support this?

See above 😄
