### ISSUE TITLE
Data URLs are incorrectly intercepted

### ISSUE THREAD

**Issue by kaciakmaciak** [kettanaito/msw#1623]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v19.7.0

### Reproduction repository

https://codesandbox.io/p/sandbox/elated-voice-ru69gu

### Reproduction steps

Fetch any data URL (URL with data schema).

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs

### Current behavior

The data url is being intercepted by `msw/node`.

### Expected behavior

The data url should not be intercepted by `msw/node`.

**Comment by kettanaito** [comment]
Hi, @kaciakmaciak. 

Since you are performing an actual `fetch` request with the given Data URI, it _will_ be intercepted. You can see that it results in a regular Network request in the browser:

<img width="900" alt="Screenshot 2023-05-25 at 10 14 16" src="https://github.com/mswjs/msw/assets/14984911/f62a4a1a-354f-4f80-8d64-d20c2108e9ff">

Anything that's a real Network request should and will be intercepted by MSW. There appears to be no issue here.
