### ISSUE TITLE
Set Content-Length header when using context.body or context.json

### ISSUE THREAD

**Issue by chriswilty** [kettanaito/msw#1658]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Using Context.json() sets the body and the Content-Type header, but not the Content-Length header. This means I need to manually set that header, because my implementation code checks it to determine whether or not there is a body. This in turn makes the Context.json() function a bit pointless for me, as I would need to stringify my mock body in order to set an accurate content-length, so then I may as well use Context.body() and set both headers.

Workarounds (for my use case):
- test code can set any non-zero value for Content-Length, and use Context.json()
- as fetch() returns a ReadableStream as body, implementation code can read from that and checks if it's empty, rather than checking the content-length header (feels marginally less efficient)

Can you foresee any problems in setting this header based on the length of the generated body string? I suppose technically it could be a breaking change? For consistency you'd also want to set it with the other body setters, so the proposal scope is wider than just the Content.json() function.

**Comment by kettanaito** [comment]
Hi, @chriswilty. Thanks for the proposal, I think it makes perfect sense! 

Since it's a new behavior, I will address it post v2.0 launch. You can upgrade to the next version of MSW by following this discussion #1464. 

The change itself will be a matter of setting the `Content-Length` header as a part of `HttpResponse.json()` (and other) [static methods](https://github.com/mswjs/msw/blob/59c3e5286a319a9b0cd87424bf0c2890b631a735/src/core/HttpResponse.ts#L64C65-L64C65). 

I wouldn't touch this until the 2.0 lands to keep the release's scope manageable.

**Comment by kettanaito** [comment]
I propose we do the following:

- If the `Content-Length` header is not provided, MSW infers it from the given text/JSON body.
- If the `Content-Length` header is provided, MSW uses that value and opts out from any inference. 

Since `HttpResponse.text()` and `HttpResponse.json()` _must_ accept a serializable body, we can always infer its length just by calculating that body's length. Those static methods don't accept non-serializable body types like `ReadableStream` or `File`. You need to use `new HttpResponse(streamOrFile)` to send those bodies in the response, and with that, provide the `Content-Length` header yourself.

**Comment by kettanaito** [comment]
> Can you foresee any problems in setting this header based on the length of the generated body string?

The only thing I see as a problem is that the standard `Response.json()` static method does not set the `Content-Length` response header for you, only the `Content-Type`. If `HttpResponse.json()` now also sets the `Content-Length` for you, we have a behavior deviation from the standard we are extending. Those deviations are fine to a degree; if they provide developer convenience without introducing a significant expectation shift. Perhaps we need to discuss this behavior a bit more before shipping this, I may not predict all the possible implications here. 

> I suppose technically it could be a breaking change?

This isn't a breaking change. The presence of an inferred `Content-Length` response header must not break consumers. Consumers must be ready for both states when such a header arrives and doesn't arrive from the server (which we are describing with MSW). Moreover, servers will often infer `Content-Length` and send it to the client. By adding this inference to MSW, we are _fixing_ a compliance issue with the actual server behavior. 

> For consistency you'd also want to set it with the other body setters, so the proposal scope is wider than just the Content.json() function.

I suggest we limit the proposal's scope to the following static methods:

- `.text()` (can calculate from the body string);
- `.json()` (can calculate from the stringified body);
- `.xml()` (can calculate from the body string);
- `.arrayBuffer()` (can get the buffer's `byteLength` property).

We omit the `.formData()` static method because it becomes problematic for MSW to infer the `Content-Length` from that. You may be sending strings, files, and all sorts of things in a form data, so you must provide the `Content-Length` yourself in that case.

**Comment by kettanaito** [comment]
We are already setting `Content-Length` on `HttpResponse.arrayBuffer()`:

https://github.com/mswjs/msw/blob/2af274c154d2e0b696188c10ba1f0271e900c40a/src/core/HttpResponse.ts#L104-L106

**Comment by thedanchez** [comment]
> We are already setting `Content-Length` on `HttpResponse.arrayBuffer()`:
> 
> https://github.com/mswjs/msw/blob/2af274c154d2e0b696188c10ba1f0271e900c40a/src/core/HttpResponse.ts#L104-L106

@kettanaito  Can we expect the same to be done for `text()`, `json()` and `xml()` ?

**Comment by kettanaito** [comment]
@thedanchez, we can but we still have to evaluate the danger here. The danger being that standard shorthand methods like `Response.json()` _don't_ set the `Content-Length` response header. I'm okay with MSW shipping convenience features, in the end, `.text()` and `.xml()` and other static methods are also non-standard. Just need to be sure that people's expectations are correct when using them. 

I think we can safely state that if you provide a response body, there's a very slim chance you'd want the `Content-Length` of that body to be anything different than the actual body's length. I think it's safe to calculate that on MSW's side and set the `Content-Length` response header for the user. 

> If the user provides an explicit `Content-Length` header, that value will be used instead. 

🟢 I'm giving this a green light. This can be a good feature for 2.1.

**Comment by kettanaito** [comment]
## Released: v2.2.0 🎉

This has been released in v2.2.0!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.2.0)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.2.0)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by ZeroCho** [comment]
@kettanaito First, thank you for your work to improve MSW!

I have an issue with `2.2.0+` version of MSW, when I put CJK(Chinese, Japanese, Korean character) in MSW response.
Until `msw@2.1.0`, it was fine. I checked out what was changed in 2.2.0, and I found this commit could be the problem.

For example, the length of string '조현영'  (which is Korean) is 9 bytes in network, whereas 'abc' is 3 bytes. But both are 3 lengths in JavaScript. I think current implementation which calculate length by just `string`.length can be problem.
I think using `new TextEncoder().encode(str).length` would be better to calculate `Content-Length`. Thank you

<img width="358" alt="image" src="https://github.com/mswjs/msw/assets/10962668/e572955f-9eb6-4f18-840b-8730e87d89f5">

**Comment by kettanaito** [comment]
@ZeroCho, thanks for the additional info! I confirm we should be using byte length for the `Content-Type` header. If this sounds interesting to you, please open a pull request to MSW. I've described a few ways we can solve this in #2045. Thanks.
