### ISSUE TITLE
Multiple handlers in a single test

### ISSUE THREAD

**Issue by james-wee-iress** [kettanaito/msw#1710]
### Scope

Adds a new behavior

### Compatibility

- [X] This is a breaking change

### Feature description

I'd love to be able to use multiple handlers on the same URL inside a single test statement. 

E.g.
```
test('should handle batch request two times, () => {
  server.use(rest.post('/batchEndpoint', (req, res, ctx) => res.once(ctx.json({ a: 1 }))));
  server.use(rest.post('/batchEndpoint', (req, res, ctx) => res.once(ctx.json({ b: 2 }))));

  // ... Tests below
})
```

The outcome of this is
- First response should be `{ a: 1 }`
- Second response should be `{ b: 2 }`

I'd love to also suggest `server.useOnce` instead of `res.once` as a breaking change because I think using API like this is a nice way to reuse handlers. But this is less priority than the above. 
```
server.useOnce(batchEndpointHandler({ a: 1})); 
```

**Comment by kettanaito** [comment]
Hi, @james-wee-iress.

The behavior you are suggesting is already supported. Providing multiple one-time handlers for the same resource will behave as you described.

```js
test('should handle batch requests two times', async () => {
  server.use(
    rest.get('/resource', (req, res, ctx) => res.once(ctx.text('Hello'))),
    rest.get('/resource', (req, res, ctx) => res.once(ctx.text('World')))
  )
})
```

The first `GET /resource` request performed in your test will received the `"Hello"` text response. Since that's a one-time handler, it will immediately be marked as used and won't affect the traffic anymore (until you call `.restoreHandlers()`). The next `GET /resource` request will be handled by the second matching handler, sending the `"World"` text response to your tested application. 

Any subsequent requests to `GET /resource` won't be handled by either of those runtime handlers, and will rely on whichever handlers you have provided during the `setupServer()` call. 

> I'd love to also suggest server.useOnce instead of res.once as a breaking change because I think using API like this is a nice way to reuse handlers.

Thanks for the suggestion! I've looked into this as well and with MSW 2.0 the one-time handlers will be defined like this:

```js
http.get('/resource', () => new HttpResponse('Hello'), { once: true })
```

You can start using the next version of MSW today by upgrading to `msw@next`. Learn more in #1464.
