### ISSUE TITLE
Add support for `Response.error()` to trigger network errors

### ISSUE THREAD

**Issue by weyert** [kettanaito/msw#1722]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

In v2 of `msw` a different approach for defining handlers exists, before we had a function called `networkError('blah')` and in v2 there is a class named `NetworkError` to offer similar functionality.

I would like to propose to add support for the static method `HttpResponse.error()` (or `Response.error()`) as mentioned at https://developer.mozilla.org/en-US/docs/Web/API/Response/error_static which is the 'browser-way' to create a network error, I quote:

> The error() static method of the [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) interface returns a new Response object associated with a network error.
> 
> This is mainly useful when writing service workers: it enables a service worker to send a response from a [fetch](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/fetch_event) event handler that will cause the [fetch()](https://developer.mozilla.org/en-US/docs/Web/API/fetch) call in the main app code to reject the promise.

**Comment by kettanaito** [comment]
Thanks for raising this, @weyert! Since our discussion, I kept thinking if we don't already extend the native Response with HttpResponse and it does seem to be the case:

https://github.com/mswjs/msw/blob/3fb29e5dd41650db1d92bf4aeae4b5a34bb073f4/src/core/HttpResponse.ts#L31

This means that we already have `HttpResponse.error()` transitively right now on the latest `next` release tag. I think no additional changes are necessary apart from removing the `NetworkError` and adjusting the migration guide.

**Comment by kettanaito** [comment]
`Response.error()` also seems to be supported in Node.js so it won't be a browser-only way to create a network error response.

**Comment by Steadyx** [comment]
Hey,

I've been following the discussion on adding support for `HttpResponse.error()` to trigger network errors, and I'm interested in contributing to this feature. Just a few things.

From the discussion I've seen so far it appears that `HttpResponse` already extends the native `Response` class which from what I assume could indicate that `HttpResponse.error()` could already exist due to inheritance. 

If this is the case and we've verified that the `HttpResponse.error()` works like @weyert described then the changes for all of this should be fairly straightforward to implement. If possible I'd be more than happy to create a PR for this.

**Comment by kettanaito** [comment]
@Steadyx, we would certainly appreciate your help and expertise! 

> From the discussion I've seen so far it appears that HttpResponse already extends the native Response class which from what I assume could indicate that HttpResponse.error() could already exist due to inheritance.

You assume correctly. No implementation should be necessary but we do have to add tests to make sure `HttpResponse.error()` behaves just like the `NetworkError` class does right now. Once that's the case, we should remove the `NetworkError` class and update the `MIGRATING.md` docs. Does this sound like a task you'd be interested in tackling?

**Comment by Steadyx** [comment]
Hey yeah, I'm on it.

**Comment by kettanaito** [comment]
I had a minute yesterday and I added this support in #1730. We can consider this closed.
