### ISSUE TITLE
Type error on server.close()

### ISSUE THREAD

**Issue by blordpluto** [kettanaito/msw#1752]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

18.12.2

### Reproduction repository

https://codesandbox.io/p/sandbox/blazing-meadow-dn6x36?welcome=true

### Reproduction steps

I am working through troubleshooting errors that come from a bump from `jest` 29.5.0 to 29.7.0 and from `msw` 1.2.2 to 1.3.1.

I am on `ts-jest` 29.1.1

With the following, copied from your suggested Jest setup:
```typescript
// serverMock.ts

// Setup adapted from https://github.com/mswjs/examples/blob/master/examples/with-jest/jest.setup.js

// Polyfill "window.fetch"
import 'whatwg-fetch';
import '@testing-library/jest-dom';
import { setupServer } from 'msw/node';

const server = setupServer();

beforeAll(() => {
  server.listen({
    onUnhandledRequest: 'error',
  });
});

afterEach(() => {
  server.resetHandlers();
});

afterAll(() => {
  server.close();
});

export default server;
```

### Current behavior

I get the following error on a jest run:

```sh
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'XMLHttpRequest')

      19 |
      20 | afterAll(() => {
    > 21 |   server.close();
         |          ^
      22 | });
      23 |
      24 | export default server;

      at node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/index.ts:55:36
      at XMLHttpRequestInterceptor.Object.<anonymous>.Interceptor.dispose (node_modules/@mswjs/interceptors/src/Interceptor.ts:195:9)
      at node_modules/@mswjs/interceptors/src/BatchInterceptor.ts:46:49
      at BatchInterceptor.Object.<anonymous>.Interceptor.dispose (node_modules/@mswjs/interceptors/src/Interceptor.ts:195:9)
      at SetupServerApi.close (node_modules/msw/src/node/SetupServerApi.ts:160:22)
      at Object.<anonymous> (internals/jest/serverMock.ts:21:10)
```

### Expected behavior

The suite appears to run (and pass!) if I delete the `afterAll` block:

```typescript
afterAll(() => {
  server.close();
});
```
entirely, but I am reluctant to do so. 😄 

Thanks in advance for any guidance.

**Comment by kettanaito** [comment]
Hi, @blordpluto. Thanks for reporting this. 

Sorry, I don't see how to reproduce it in the sandbox you've linked. Do you have any steps I need to follow? Those would help. 

The error itself suggests that `window.XMLHttpRequest` fails because `window` is `undefined` in your test. This is strange since we guard against it in the Interceptors:

https://github.com/mswjs/interceptors/blob/edd2217e181a09cb4bf57b35662a2b24ebeac28c/src/interceptors/XMLHttpRequest/index.ts#L23-L24

It would help if you could also answer these questions:

1. What test environment are you running (Node/JSDOM)? Make sure you're using JSDOM if you're testing browser-oriented code. 
2. Why do you export `server` from the Jest setup file? That's a bad idea. Instead, create something like `node.ts` and adjust your test setup like this:

```ts
// node.ts
import { setupServer } from 'msw/node'
import { handlers } from './handlers' // if you have base handlers

export const server = setupServer(...handlers)
```

```ts
// serverMock.ts
import { server } from './node'

// This setup remains the same.
beforeAll(() => { ... })
afterAll(() => { ... })

// No "server" exports from here.
```

This may help, try this.
