### ISSUE TITLE
Unit test - setupServer with Supabase url - onUnhandledRequest: 'warn' does not capture any request yet the account is still created

### ISSUE THREAD

**Issue by morcth** [kettanaito/msw#1763]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v18.17.1

### Reproduction repository

https://github.com/morcth/msw-issue

### Reproduction steps

npm install
npm run test

You will see in the condole that MSW sees the google call with no handler. Ignore the typeerror about the fetch. No other calls are seen or captured.

This is using the imported Supabase client created in supabase.js located in the src directory. It is imported in the App.vue file.

Now, please go into the supabase.js file and copy it all into the App.vue below the "ref" import.
Remove the supabase import, and the "export" keyword in from of the supbase = createClient

Save and test again.

You will  see in the terminal that 2 Supabase calls are now seen and captured along with the google call. 

### Current behavior

The calls from the Supabase client are only seen if the client is created in the component being rendered for the test.
If the client is created in a different file and imported in, the calls are invisible to msw. 

Because of this, the calls go through. Test users do get created in my account. 

Is this how msw is supposed to work or is it a bug? Hopefully there is a way to not need to create the client in each component that communicated with Supabase. I'm guessing that will trigger some errors anyway.

### Expected behavior

The Supabase calls are seen by msw whether the client is created in the component or imported in.

Thanks!

**Comment by mattcosta7** [comment]
It appears that calling `createClient` in supabase immediately emits fetch requests

https://github.com/supabase/supabase-js/blob/54c552d802ddcfb241db7960fe51ab2e56334494/src/SupabaseClient.ts#L112-L117

because of this, when you're importing it into your vue application/components, since imports are evaluated immediately, and fetch is evaluated immediately, you're initializing the request before your test code is evaluated, which is why these are not captured. 


I'm sure there are many ways to work around this. One that might require the least code change (at least to validate)

```tsx
-  import App from "../../App.vue";

...


  test("fetches and displays Todos", async () => {
+   const {default: App} = await import("../../App.vue");
    render(App);
    //await waitForElementToBeRemoved(() => screen.queryByText("Loading..."));
    const button = screen.getByRole('button', {name: 'Add todo' });
    await userEvent.click(button);
    expect(await screen.findByText(todos[0].name)).toBeInTheDocument();
  });
```

from there you might consider calling createClient in a top level component and I believe vue has some concept of context/stores that could hold it (I'm not familiar enough with vue to offer more guidance there). 

This would avoid creating the client until the app is rendered - albeit this may not be ideal for your usecase, in which case this lazy load of app in your tests would avoid that code being evaluated prior to the server/listener  being created

**Comment by morcth** [comment]
Thank you for the quick response and the fix, @mattcosta7! 

This worked! I do not have to change the app code at all... all changes are done in the test files.

The only issue is now ALL test functions need to be async and I have to add 
`const { default: ComponentName} = await import('../ComponentLocation.vue');` to every test

Anything you can think of that might help me not have to do that... or what terminology should I maybe search for to find a different way?
I tried putting the await import into BeforeAll or BeforeEach but it gave me some attitude... maybe I can put something into the file where I export the supabase client?

Any help is much appreciated!
Josh

**Comment by mattcosta7** [comment]
> Thank you for the quick response and the fix, @mattcosta7! 
> 
> This worked! I do not have to change the app code at all... all changes are done in the test files.
> 
> The only issue is now ALL test functions need to be async and I have to add 
> `const { default: ComponentName} = await import('../ComponentLocation.vue');` to every test
> 
> Anything you can think of that might help me not have to do that... or what terminology should I maybe search for to find a different way?
> I tried putting the await import into BeforeAll or BeforeEach but it gave me some attitude... maybe I can put something into the file where I export the supabase client?
> 
> Any help is much appreciated!
> Josh

I think there are many ways to go about this. 

one could be a lazy-init function for the client

```
let supabaseClient;

export function getSupabaseClient() {
   if (supbaseClient) return supabaseClient
   const client = createClient(...)
   supabaseClient = client
   return client
}
```

then in your vue components, you can use this getter to avoid evaluating the client generation eagerly, since importing the getter won't immediately call createClient, but instead it only gets called when the first attempt to interact with that client occurs


This delays that initial call in production code though, which I think you could work around by just calling that getter from your entry point before app startup.  This would allow any component in a test to lazily create the client, but in production move that lazy evaulation to just occur very early

There are many other options here, so just suggesting this as one potential idea (with the caveat, I haven't written any vue in ~6 years nor used supabase, and I don't know your applications constraints)



that said, I don't think there's anything wrong with making all of the test async and adding that line - it's the 'correct' way to go about this from the perspective of only evaluating after setup based on the module level definiton of the client - ie, there is no way to parse the file without executing the side effects

**Comment by kettanaito** [comment]
I'm closing this because this isn't something we should address on MSW's side. 

You have to ensure that MSW is imported and _enabled_ prior to any code that dispatches requests (if that's what you wish, of course). The order of imports is on the developer's side.
