### ISSUE TITLE
TypeScript error with different `return HttpResponse.json()`

### ISSUE THREAD

**Issue by nix6839** [kettanaito/msw#1792]
- MSW version: `v2.0.0`
- TypeScript version: `v5.2.2`

## Problem
I get an error when I return two different JSONs using `HttpResponse.json()` and a `if` statement. e.g.
```ts
import { HttpResponse, http } from 'msw';

http.get('/', ({ cookies }) => {
  const { v } = cookies;

  if (v === 'a') {
    return HttpResponse.json({
      foo: 'a',
    });
  }

  return HttpResponse.json({
    bar: 'b',
  });
});
```

Getting following error message:
```log
Argument of type '({ cookies }: ResponseResolverInfo<HttpRequestResolverExtras<PathParams>, DefaultBodyType>) => StrictResponse<...> | StrictResponse<...>' is not assignable to parameter of type 'ResponseResolver<HttpRequestResolverExtras<PathParams>, DefaultBodyType, { foo: string; }>'.
  Type 'StrictResponse<{ foo: string; }> | StrictResponse<{ bar: string; }>' is not assignable to type 'AsyncResponseResolverReturnType<{ foo: string; }>'.
    Type 'StrictResponse<{ bar: string; }>' is not assignable to type 'AsyncResponseResolverReturnType<{ foo: string; }>'.
      Type 'StrictResponse<{ bar: string; }>' is not assignable to type 'StrictResponse<{ foo: string; }>'.
        Property 'foo' is missing in type '{ bar: string; }' but required in type '{ foo: string; }'.
```

[Reproduction in TS Playground](https://www.typescriptlang.org/play?jsx=0#code/JYWwDg9gTgLgBAbzgCRjMAlApgZ0gOxywBo4ALNMOAXzgDMoIQ4ByEHAdxYG4AoXiugB0AcywwAFCwD0LUhKQBjCBADWwXDQCUcALwA+RLzhxlheEgBuNPaZXrcfY3GB04E67q+sAhix0IziZQ4gCuUPgolNh4EIRYQgBWOHEKQSb0KgBcvnLp1Fp8JtT8wWERUegxBERJKfhpGXAARj5QOSzNecWFvAV8QA)

## Temporary workaround
If explicitly add at least one generic like this, it will work fine:
```ts
import { HttpResponse, http } from 'msw';

http.get<never>('/', ({ cookies }) => {
  const { v } = cookies;

  if (v === 'a') {
    return HttpResponse.json({
      foo: 'a',
    });
  }

  return HttpResponse.json({
    bar: 'b',
  });
});
```

## Expected Behavior
I want type inferring to work without explicit adding generics.

**Comment by mattcosta7** [comment]
@nix6839  I think you'd want generics like these for a proper workaround

https://www.typescriptlang.org/play?jsx=0#code/JYWwDg9gTgLgBAbzgCRjMAlApgZ0gOxywBo4AFAQxgAtKoKQdSARLAMwoFcAbGAIQgATAJ4AVYWBJxqaMHAC+cNlAgg4AckYB3dQG4AUPpnoAdAHMsMADyUadBkzisOPfkLESpCNhAgAuOBwYKGB8M0UAH0QAIwooAKCQsPkAPgAKdQB6dVI0pABjXwBrYFwFAEo4AF4UxH04OELCeCQANwVqxuLSnAN6uGA2ODT2qrGNCnVKhH6GqEtOKHwUWWw8CEIsEwArHA282YalXwD1SeJD+XKDBvlDOYWllfQ1giIdvfwDo7hY+I1ojl+lcDCD9EA

but we should probably make this work by default instead of inferring just the first return type only

**Comment by ScottGuymer** [comment]
I have also just ran into this and its quite confusing when migrating form 1.0 > 2.0.

I have a handler something like this

```
const handlers = [
  http.get('http://localhost/api/user_groups/search', ({ request }) => {
    const url = new URL(request.url);
    const searchGroups = url.searchParams.get('q');

    if (searchGroups == 'testGroup') {
      return HttpResponse.json({
        groups: [
          {
            name: 'testGroup',
            membersCount: 10,
            managed: true,
          },
        ],
      });
    } else {
      return new HttpResponse(null, { status: 404 });
    }
  }),
];
```

In which even the workaround of using `<never>` doesn't work as `HttpResponse.json()` and `new HttpResponse()` seems to be incompatible or at least could not find the correct types to define in the generics to make it all work.

**Comment by mattcosta7** [comment]
> const handlers = [
>   http.get('http://localhost/api/user_groups/search', ({ request }) => {
>     const url = new URL(request.url);
>     const searchGroups = url.searchParams.get('q');
> 
>     if (searchGroups == 'testGroup') {
>       return HttpResponse.json({
>         groups: [
>           {
>             name: 'testGroup',
>             membersCount: 10,
>             managed: true,
>           },
>         ],
>       });
>     } else {
>       return new HttpResponse(null, { status: 404 });
>     }
>   }),
> ];

Can you make a typescript sandbox that shows the error you're seeing. 

this seems to compile fine here: https://www.typescriptlang.org/play?jsx=0#code/JYWwDg9gTgLgBAbzgCRjMAlApgZ0gOxywBo4AFAQxgAtKoKQdSARLAMwoFcAbGAIQgATAJ4AVYWBJxqaMHAC+cNlAgg4AckYB3dQG4AUIZnoAdAHMsMABTrjYAFwB6R9wgBjCt2oQcMRxTBgR04iKAB9MxVOMBxHIgooN2p1UiskKCwAR05ceHkASjgAXgA+RH04ODcIQnhOKG5iuHwsLTgAVQwAGSsM7NyTeu58g0rq2rh4xOoAcSiYpqGTKaS6BhxzSxtM9RHDSuA2OCsV2fmcYqKNGFy5iGjd8srKjJh6-BRZbDwaohMAKxwNTSFWelUi9xi9jgAG1QWDKgh4QjKvgGFhoeobr47g9iMiUSAsCAAEZYKA4ADC93wMGhAEYAAz4lFgkAUNEWQTQmBQHIs1nyAVggC6woUe0qiiw3CIT2er3ezVan3Q3wIRCs+B43FISF8VBC0IALIzjRLQfJ9AUgA

but maybe there's something else I'm not aware of?



edit - if you needed to type it explicitly, something like https://www.typescriptlang.org/play?jsx=0#code/JYWwDg9gTgLgBAbzgCRjMAlApgZ0gOxywBo4AFAQxgAtKoKQdSARLAMwoFcAbGAIQgATAJ4AVYWBJxqaMKQDKMKMADGMbHgiEscAL5w2UCCDgByRgHdTAbgBQ9megB0AcywwAPJRp0GTOKwcPPxCYhJS+FgAblhQcAA+cBoERAIiAHwAFKaOYABcAPQF3BAqFNzUEDgwBRRgwAWcRFAA+i5GnGA4BUQUUCrUpqSZSFBYAI6cuPC6AJRwALzpiLZwcCpa1XCcUNyLcJEWcACqGAAymWOT00473LN2axuE8L391ADiHV37d05vA18jFc7my41MD3sa2AbDgmQBn2+OEWCzMMGmXwgnQhKzWazGMB2+BQsmSmywTgAVjgtCNVni1u0sV08nAANr0hlrBCcrlrfAMLCs0zo6qY7HEXl8kBYEAAI1iOAAwlj8DBWQBGAAMkr5DJAFAFbkErKUU11et0FoZAF1rXpIWtdPSCUSDlgjqh0GTtJl8DxuKQkNUqE1WQAWLXhh1wCjIxTKNQ+ogeSIxKDpem2Ob2GDhJK4FJYNLCfY8hlMzo4VnlvUCmWs6rKfAuR56mXyxUqzhq1n+ztQNvSw0UY2suUQCDcLCGod6Nk27NAA should be ok.   `StrictResponse` and `HttpResponse` might not both play nicely in types when mixed but casting `HttpResponse` objects should be fine

**Comment by kettanaito** [comment]
Looks like a duplicate of #1691. MSW needs to do a better job at _inferring_ union response body types. 

## What should I do now?

For now, annotate the response body type union explicitly as @mattcosta7 suggested above.

**Comment by ryota-murakami** [comment]
Why MSW infer parameter and strong typed even you don't give generics for response body?
`get<T = any>` is doesn't make sense?

**Comment by Andarist** [comment]
I'll leave here what I investigated while being pinged on Twitter.

TS doesn't attempt to unionify inference candidates gathered from positions that don't imply combinations (`PriorityImpliesCombination = ReturnType | MappedTypeConstraint | LiteralKeyof`). Since you try to infer `T` from expressions like `return {} as AsyncResponseResolverReturnType<{ foo: string }>` this inference doesn't imply those combinations. Yes, they appear at return positions but not directly. 

So in your example, it tries to find a common supertype of all gathered inference candidates but since there is no such supertype it just picks up the first candidate. You can roughly see this in the source code [here](https://github.dev/microsoft/TypeScript/blob/27556f5d3bc4cd3797efe31d32f45775e2a1ca75/src/compiler/checker.ts#L25919-L25923)

There is not much that you can do to overcome this beyond convincing the TS team to use different heuristics for this stuff 😉 

However, if you'd change your generics to infer what might appear directly at those return positions and then maybe unpack the contained type then it could work. You can see what I mean by inspecting the fourth example at the bottom [here](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwxAGcMBGAHgBUA+ACjACMAueWgSngF5r5K2XKAbgBQwsHhLw4RZBDJcCxMrXZceAb2Hx4WRKwCyUDAAsAdDCipgOALbsOm7drgZkMfI6fbEOHCwBE-gA0Wk4AviLaYaLOIK7u8J7aDLAspAAM6SFRImFsIsLSsmQiAPSl8AB6APyi4qiSRXIATAqEJKQqHNyJoboGRmYWVrb2vV4ubh5h8FBE415IviwkMFioAOaR4dvRoZMJ6jNzC8mp8KjINgwgMLu5+aJNGM1lFTWiGACeAA4IAEI4AAeVB4nAWADcBLkCqBILAECh0Ng8IoSABmUH0Zisbo8QEgmj8XgFeqNYjFdFtJTorpqBb9WiGEzmSzWOxsByhWLxaazeYE8hJJw+PzwVbrLbc+Bhai7GJSOJTRLHAXAoXSlIwFiXa63XZy4R5ArPdFvKq1YRw6BwJBoTC4fDtDAAFio8BAQMIVjVILQAGtUDgAO6oah0RgsVQ9PgCADa-gh-gAuqSJBhFTI5C7qSQXXSep5GcyhmzRpzToreSr+fBBcLvMtxRg1pttlFDVEFQc+Sd65rzrqbndQrKHiaKdnzR8gA)

**Comment by michaeltroya** [comment]
My quick workaround here has been to do

```
import { HttpResponse, http } from 'msw'

http.get('/', ({ cookies }) => {
  const { v } = cookies

  return HttpResponse.json(v === 'a' ? { foo: 'a' } : { bar: 'b' })
})

**Comment by mattcosta7** [comment]
Another example that reads a bit better might be

> My quick workaround here has been to do
> 
> ```
> import { HttpResponse, http } from 'msw'
> 
> http.get('/', ({ cookies }): StrictResponse<{foo: 'a'} | {bar: 'b'}> => {
>   const { v } = cookies
>   if (v === 'a') return HttpResponse.json({foo: 'a'})
>   return HttpResponse.json({bar: 'b'})
> })
> ```

it requires an explicit type for the return value, once, but avoids needing to deal with other generics

**Comment by kettanaito** [comment]
@mattcosta7, can't one achieve the same by providing the response body as the `ResponseBody` generic to `http.get`?

```ts
http.get<never, RequestBody, { foo: 'a' } | { bar: 'b' }>('/', resolver)
```

**Comment by mattcosta7** [comment]
> [@mattcosta7](https://github.com/mattcosta7), can't one achieve the same by providing the response body as the `ResponseBody` generic to `http.get`?
> 
> http.get<never, RequestBody, { foo: 'a' } | { bar: 'b' }>('/', resolver)

yep - they definitely can, but then you need to add types for the generics describing the path parameters and body.  By annotating the return type, you avoid needing to add the extra generics.

**Comment by kettanaito** [comment]
I recommend using the generics for this. That way you get a complete type-safe request handler. By annotating the return type of the resolver alone, you are tapping into implementation details (`StrictResponse`), which is not a future-proof strategy.

**Comment by kettanaito** [comment]
## Solution

Use an explicit response body generic to describe response body union types (as mentioned [here](https://github.com/mswjs/msw/issues/1792#issuecomment-1799056048)). The inference behavior you experience is caused by the way TypeScript evaluates unions. There's nothing we can do on MSW's side. 

- Learn more about [Using MSW with TypeScript](https://mswjs.io/docs/best-practices/typescript)

**Comment by kettanaito** [comment]
## Update

With #2439, you will be able to tap into a type-unsafe response declaration with `new HttpResponse()`. This doesn't directly fix the issue but allows you for a proper type-checking when it comes to declaring error responses, for example.
