### ISSUE TITLE
Types refer to missing global interface ResponseInit

### ISSUE THREAD

**Issue by thw0rted** [kettanaito/msw#1836]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v20.9.0

### Reproduction repository

https://github.com/thw0rted/issue-examples/tree/msw-ResponseInit

### Reproduction steps

`npm install`, `npm run build`

### Current behavior

Several MSW types extend globals that come from the stock Typescript `lib.dom.d.ts`.  Without lib-dom (`lib: []` in tsconfig) these types will generate an error if `skipLibCheck` is false, or fail in consuming code if `skipLibCheck` is true, as in my repro.

### Expected behavior

MSW types should not refer to global types that come from `lib.dom.d.ts` but are not in `@types/node`.  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66824 added the actual function/class/object types that are exposed at runtime by modern Node (`fetch`, `Request`, `Response`, etc) but did not add fictional "helper" interfaces that, as far as I can tell, were invented by the TS team to reduce redundancy, like `RequestInit` / `ResponseInit`.

One possible workaround here would be, instead of extending global interfaces, create an alias to the parameter type extracted using e.g. 

```
type CC = ConstructorParameters<typeof Response>[1];    // second argument to constructor is the init-object
type CS = CC['status'];                                 // should be "number" in both Node and DOM environments
type JJ = Parameters<typeof Response.json>[1];          // as above for static `Response.json` method
type JS = JJ['status'];                                 // same
```

This would work regardless of whether Response is declared using a helper alias for the init-object or not.

----

Also, it might be worth turning off `skipLibCheck` and examining the other compiler errors that this exposes, related to the global `File` object, which does not exist in Node 18 but appears to have been added in Node 20.  Not sure if you'd want a new issue for that.

**Comment by thw0rted** [comment]
Re: the last comment about skipLibCheck, you could consider setting up an alternate `tsconfig` file which omits lib-dom and adding a build-without-DOM step to your CI, which would catch this sort of thing in the future. I know running without lib-dom is pretty unusual today, but I hope to see it become more mainstream as the Node-only types improve.

**Comment by kettanaito** [comment]
Hey, @thw0rted. Thanks for reporting this. I believe this is the same as https://github.com/mswjs/msw/issues/1819#issuecomment-1789364174, please see my comment there. 

> MSW types should not refer to global types that come from lib.dom.d.ts but are not in @types/node.

This is precisely what MSW does now. In its `/node` export, there's no dependency on `lib.dom`, it doesn't exist in `tsconfig`. The issue here is that `@types/node`, in my experience, do not create the proper global types like `ResponseInit`. I raised it in DefinitelyTyped but the team there simply suggests installing `@types/node` to auto-fix the issue. That didn't work for me, try if it works for you. 

The issue is that the `ResponseInit` global type is missing from your Node.js environment. If MSW was bundled with `lib.dom`, that issue wouldn't have occurred but your Node.js environment would be polluted with DOM-specific global types. That's not the case anymore and we've fixed that since 2.0. But that also means that now _you_ have to make sure your environment has the correct types. 

I've mentioned one way to fix that in the comment, which is adding `lib.dom`. Not perfect, I know, but I found it to be the most straightforward solution. If `@types/node` works for you, _use that_. TypeScript also adds `lib.dom` _by default_ to any TS project, which, I want to believe, is a heavily thought-through default that should be safe to rely on. 

> but did not add fictional "helper" interfaces that, as far as I can tell, were invented by the TS team to reduce redundancy, like RequestInit / ResponseInit.

They did. The DefinitelyTyped team has added those types in `@types/node` but I think there's an issue in how they are exposed. They are never exposed as globals, so you never get them as such. 

> Also, it might be worth turning off skipLibCheck and examining the other compiler errors that this exposes

I think this is not advised. Checking lib can expose all sorts of issues that have nothing to do with MSW. As an example, there are libraries that ship broken type definitions (may be related to particular TS versions), and MSW isn't the surface that should care or address those errors. 

What we _can_ do is set up a typing test aimed at Node.js without the `lib.dom` default library.

**Comment by thw0rted** [comment]
Weird, I swear I searched for previously reported issues and came up empty.  Thanks for the link.

I did some more digging and it looks like `ResponseInit` actually does appear in the [non-normative section of the whatwg spec](https://fetch.spec.whatwg.org/#responseinit).  That spec includes multiple "Init" interface definitions in the form of "dictionary" and "typedef" entries.  I believe `lib.dom.d.ts` exposes all of them globally.  Originally I thought the Typescript folks came up with those names while capturing `fetch` types, but finding them in the spec probably gives more weight to the argument that `@types/node` should expose them all as well.  I will follow up with DT about adding them to the [existing global export for RequestInit](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/globals.d.ts#L348).  Basically it looks like omitting ResponseInit was probably an oversight in the original PR.

----

Regarding turning off `skipLibCheck`, if you try it out in my repro you should find errors only in `msw` because it has very few deps installed.  I think once I get the various Init types squared away, the only remaining error will likely be due to a missing global File type, which needs to be fixed in `@types/node` anyway.  Still, would be neat to have a standing no-lib-dom types test as you describe.

**Comment by thw0rted** [comment]
I think https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67341 will fix it 👍🏼

**Comment by cdaringe** [comment]
@thw0rted , i think we should keep this open. msw also has refs to other libdom types, like `File` which are (correctly?) not in node. There are a variety of globals not correctly modeled in node and referenced in msw. MSW i think probably still needs to consume only guaranteed types present in libdom and @types/node

**Comment by thw0rted** [comment]
I think that if my PR above gets merged, `@types/node` should export everything MSW uses including `File`.

**Comment by thw0rted** [comment]
Anybody watching this, you might like to know that my PR linked above just got merged.  If you update to latest `@types/node` and still have issues with missing global interfaces... open a new issue?  Comment here and re-open?  (Not my project, not sure what's preferred here.)

**Comment by SlackJaw74** [comment]
@thw0rted  I'm seeing the `ResponseInit` specific error is gone but there are still remaining types issues.

```
node_modules/.pnpm/msw@2.0.10_typescript@5.3.2/node_modules/msw/lib/core/RequestHandler-50ddea0c.d.ts:17:12 - error TS2552: Cannot find name 'ResponseType'. Did you mean 'Response'?

17     type?: ResponseType;
              ~~~~~~~~~~~~

  node_modules/.pnpm/@types+node@20.10.3/node_modules/@types/node/globals.d.ts:359:9
    359     var Response: typeof globalThis extends {
                ~~~~~~~~
    'Response' is declared here.

node_modules/.pnpm/msw@2.0.10_typescript@5.3.2/node_modules/msw/lib/core/RequestHandler-50ddea0c.d.ts:41:24 - error TS2304: Cannot find name 'BodyInit'.

41     constructor(body?: BodyInit | null, init?: HttpResponseInit);
```

**Comment by thw0rted** [comment]
Looks like both of those are more typedef/enum/alias things that exist in [the Fetch spec](https://fetch.spec.whatwg.org/) and were added to lib-dom, but as a kind of a "helper" / "fictional" type.  There was similar discussion upthread.  I think it wouldn't hurt to expose these as well in `@types/node`, but I wasn't going to bother with another round of PR reviews to add them right now, since my last round of errors got resolved.  I don't think `msw` has an action here, at least, unless they wanted to expand the aliases at point of use just for the sake of broader compatibility.
