### ISSUE TITLE
Syntax Error Prevents Code from Loading when packed in Vue/Vite app

### ISSUE THREAD

**Issue by elasticcode-ai** [kettanaito/msw#1866]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

TBD

### Reproduction steps

TBD

### Current behavior

![image](https://github.com/mswjs/msw/assets/116443122/28a8ffc5-bc4d-4794-90e1-a94658cac0fe)

### Expected behavior

To not have any code/syntax errors preventing it from loading.
Must gracefully work with Vite (like webpack for Vue)

**Comment by mattcosta7** [comment]
This issue is with the graphql package, and not in msw - so not much we can do to help:

see 
- https://github.com/mswjs/msw/issues/1645
- https://github.com/mswjs/msw/issues/1655
- https://github.com/graphql/graphql-js/issues/3928
- https://github.com/graphql/graphql-js/issues/3925

Some workarounds mentioned in those threads - such as using replace plugin to replace that string direclty

https://github.com/mswjs/msw/issues/1645#issuecomment-1801931229
