### ISSUE TITLE
MSW + Jest: Transferring of ReadableStream cannot be properly polyfilled in this engine

### ISSUE THREAD

**Issue by Samflyn** [kettanaito/msw#1931]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v21.4.0

### Reproduction repository

https://github.com/Samflyn/msw-react

### Reproduction steps

Running the App test should replicate the issue

### Current behavior

There are two requests in App, where in one with payload and the other without, the request with payload is not intercepted by msw handler while the one without payload is intercepted fine.

### Expected behavior

The request with payload should be intercepted by msw handler

**Comment by chawax** [comment]
It looks like the problem I have too : https://github.com/mswjs/msw/discussions/1915

**Comment by kettanaito** [comment]
Hi. Thanks for reporting this. @chawax, thanks for the extensive discussion. Let's get to the bottom of this. 

## Root cause

First, let's see _why_ the request fails. If we inspect the actual error preserved by Undici, we see this:

```
    DataCloneError: Transferring of ReadableStream cannot be properly polyfilled in this engine
        at throwUnpolyfillable (/msw-request-with-body-ignored/node_modules/core-js/modules/web.structured-clone.js:120:9)
        at tryToTransfer (/msw-request-with-body-ignored/node_modules/core-js/modules/web.structured-clone.js:485:9)
        at structuredClone (/msw-request-with-body-ignored/node_modules/core-js/modules/web.structured-clone.js:520:17)
        at cloneBody (/msw-request-with-body-ignored/node_modules/undici/lib/fetch/body.js:277:21)
```

This hints that Jest is having serious trouble with `ReadableStream`. 

This error is caused by `core-js`. One of our community members shared that removing `core-js` solved this error for them: https://github.com/mswjs/interceptors/issues/475#issuecomment-1790868660. 

To be more specific, this is what happens:

1. undici tries to clone the response body using the standard [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) function. This is a global function in Node.js that can clone `ReadableStream` just fine. 
```js
// node_modules/undici/lib/fetch/body.js:277:21
const out2Clone = structuredClone(out2, { transfer: [out2] })
```
2. _But_, since we are using Jest, we need to rely on `core-js` to polyfill `structuredClone`. The `structuredClone` from `core-js` just throws if the data it tries to transfer is `ReadableStream`, claiming it as unpolyfillable:
```js
// node_modules/core-js/modules/web.structured-clone.js:485:9
switch (type) {
  ...
  case 'MediaSourceHandle':
  case 'MessagePort':
  case 'OffscreenCanvas':
  case 'ReadableStream':
  case 'TransformStream':
  case 'WritableStream':
    throwUnpolyfillable(type, TRANSFERRING);
}
```

This is a bold statement, especially since we polyfill `ReadableStream` in `jest.polyfills.js`. But `core-js` never checks for that, just assumes a no-op and throws. 

The solution seems to be, once again, force Jest to use the platform, to use Node.js where things function correctly.

**Comment by kettanaito** [comment]
Jest depends on `core-js`, there's nothing we can do about that. Node.js doesn't provide the means to directly import `structuredClone`, it's set directly on the internal `messaging` [binding](https://github.com/nodejs/node/commit/4ef1d68715#diff-512ab8348327408c9a5ba3f7c60d8f8977a672a22b96345b8cfc2562936062f5R1493) in C++. No way to suggest `require('node:???').structuredClone` to "polyfill" it in `jest.polyfills.js`.

There's literally nothing I can do here. Jest doesn't respect your environment. I highly recommend you migrate away from Jest to tools like Vitest and forget about these sorts of errors. I know it's not ideal, I know migrations take time, but it's either one-time migration or lifetime of dealing with this shenanigans that nobody but Jest can properly address.

**Comment by kettanaito** [comment]
Some folks are having success by downgrading undici to v5: https://github.com/mswjs/msw/discussions/1934#discussioncomment-7912946. This may be a temporary option for those who cannot migrate to other testing frameworks as of now.

**Comment by chawax** [comment]
Yes, migrating to Vitest is definitely the only long term solution

**Comment by kettanaito** [comment]
Also a note of warning: this seems to be specific to JSDOM. `ReadableStream` and other Node.js globals work fine in Jest's `node` environment. But since `jest-environment-jsdom` isn't based on `jest-environment-node`, you don't get that. You can try swapping it with HappyDOM to see if they respect the Node.js globals better.

**Comment by chawax** [comment]
Well, I was using HappyDOM in my project, and it looks like that was the reason why downgrading Undici didn't work for me. Using Jest Environement JSDom solved instead of HappyDOM solved my problem indeed.

**Comment by kettanaito** [comment]
[Related](https://github.com/mswjs/msw/issues/1916#issuecomment-1908544946).
