### ISSUE TITLE
Patching responses of a default handler from a `use` handler

### ISSUE THREAD

**Issue by 1000hz** [kettanaito/msw#1949]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

It would be really useful to be able to passthrough a request from an overridden handler to the default handler, receive its response, and patch its data before returning it to the caller. e.g.

```diff
import { http, passthrough, HttpResponse } from 'msw'
import { setupServer } from 'msw/node'
 
const server = setupServer(
  http.get('/resource', () => {
    return HttpResponse.text('Default')
  })
)
 
server.use(
  http.get('/resource', async ({ request }) => {
+   const res = await passthrough(request)
    const body = await res.text()
    return new HttpResponse(`${body} (Augmented)`) // "Default (Augmented)"
  })
)
```

For context, I want to generate an `msw` server based on an OpenAPI schema to use in tests, and utilize `server.use()` to override response data to set up particular scenarios for each test. I'd also regenerate the server anytime the OpenAPI schema changes to keep it in sync with the real API over time. However, because the `use` handlers produce a response from scratch, _the response schema of overridden endpoints won't benefit from mock server regeneration._ Anytime we override a handler in a test, we're essentially encoding the current schema within that test. This could cause problems whenever the schema changes in a breaking way, as the test would still pass because the override is stuck in the past.

Being able to patch response data coming from a base-level handler would protect us a bit (albeit not completely) from API schema drift. Alternatively, users would need to expose and share the base handler functions so we can invoke them directly from within override handlers. Treating handlers more like middleware would potentially allow for greater flexibility when defining responses.

I suspect this would be a rather large architectural change, but maybe something to consider for the next major version. Thanks for your dedication to building a great library!

**Comment by kettanaito** [comment]
Hi, @1000hz. Thanks for raising this and sharing your use case. I have a few thoughts on this.

What you propose isn't as much a difficult technical change but rather something that goes against MSW's philosophy when it comes to request handlers. Request handlers are meant to be stateless request/response contracts. One of the fundamental characteristics of a request handler is that if it handles the request, _that's it_. This makes any handler easy to understand. There isn't anything outside of it happening, like referring to another handler elsewhere, etc. 

If we view MSW as a tool that brings control over the server, I agree that keeping request handlers like that isn't entirely faithful to how most server frameworks work. There isn't really a middleware type of behavior present in request handlers. But that's an intentional choice to keep the network description clear. 

This means that we are unlikely to adopt a middleware-like behavior in MSW.

## However

You can still implement what you described by yourself. There are a couple of ways to do that. 

### Option 1: Lift response resolution up

If you lift the response resolution "up" from the base handler, you would be able to reuse it both in the base handler and in the override handler.

```js
const state = {
  '/resource': HttpResponse.text('Base')
}

const server = setupServer(
  // You can utilize "http.all()" to resolve multiple
  // requests from the same source of truth.
  http.get('/resource', ({ request }) => {
    return state[request.url]
  })
)

server.use(
  http.get('/resource', ({ request }) => {
    const baseResponse = state[request.url]
    const body = await baseResponse.text()
    return HttpResponse.text(`${body} (Augmented)`)
  })
)
```

### Option 2: Run the base handler programmatically

You can run individual handlers against any `Request` input programmatically. 

```js
const baseHandler = http.get('/resource', () => {
  return HttpResponse.text('Base')
})

const server = setupServer(baseHandler)

server.use(
  http.get('/resource', async ({ request }) => {
    // Run the base handler programmatically to get
    // whichever response it returns.
    const baseResponse = await baseHandler.run({ request })
    const body = await baseResponse.text()
    return HttpResponse.text(`${body} (Augmented)`)
  })
)
```

The `RequestHandler` API is not standardized so it should be safe to rely on it.
