### ISSUE TITLE
Initial page load requests aren't intercepted since 2.1.0

### ISSUE THREAD

**Issue by nareshbhatia** [kettanaito/msw#1971]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/nareshbhatia/graphql-fragments-example-1

### Reproduction steps

1. Make sure that the default build with msw 2.0.14 is working (npm ci; npm run dev)
2. Update msw version in `package.json` from `2.0.14` to `2.1.0`, update mockServiceWorker.js to latest version.
3. Rebuild and run the app. It will not run.

Console shows a 405 error.

![image](https://github.com/mswjs/msw/assets/1220198/5567373f-5add-4567-baeb-bfdc6c760102)

### Current behavior

MSW is not intercepting calls

### Expected behavior

MSW should intercept calls

**Comment by skvale** [comment]
(for maintainers) 
Looks like [bringing back](https://github.com/mswjs/msw/pull/1964/files#diff-bfdee9fa341476a0f860c24550bb3304be0248d4b5cdbd4a4a272a95888d84a3L138)
```ts
    if (options.waitUntilReady) {
      deferNetworkRequestsUntil(workerRegistration)
    }
```
restores the data on initial render

**Comment by kettanaito** [comment]
Thanks for reporting this, @nareshbhatia. 

@skvale, I expect this causing issues for folks who are not [Deferring their application rendering](https://mswjs.io/docs/integrations/browser#conditionally-enable-mocking) when enabling MSW. The removed `waitUntilReady` option hackishly worked around that but it must be done by the end-developer. 

It seems that the reported reproduction repository misses that precisely:

https://github.com/nareshbhatia/graphql-fragments-example-1/blob/cccce56a2466dd082a56c8194a553f0729a2870a/src/providers/AppProvider.tsx#L14

This _isn't_ the right way to use MSW. It never was. By enabling it in a React's effect, consider when MSW actually starts:

1. Page loads.
2. Page evaluates your JavaScript.
3. (anything can make requests here)
4. Page evaluates your React code.
5. React starts rendering your app top-to-bottom.
6. (anything can make requests here)
7. React finds `<AppProvider/>` and renders it.
8. `registerMockServiceWorker` runs _but React keeps rendering in parallel_.
9. (anything can make requests here)
10. The Service Worker registers and activates.
11. (now MSW can intercept requests).

This app didn't follow the deferred rendering pattern and so it suffers from concurrency issues. 

I understand some frameworks don't provide you the means to await the worker Promise as a top-most thing in your _JavaScript_ (not even your app). Next used to give you `_app.js`, it doesn't anymore. You need to communicate with those frameworks and find ways to defer your app's rendering. This would be the proper solution to the problem. 

## Just roll back `waitUntilReady`, what's the problem?

The problem is that `waitUntilReady` was hacky. In fact, it introduced a number of client-side issues that can completely break your app in some situations (and they did, #1573). Making hacks work reliably is as painful as it is futile.

And I don't consider this a breaking change either. Breaking changes are those that contradict the promise made by the library. The promise was always to await the worker and then render your app. `waitUntilReady` was a hack for those who couldn't do that five years ago. The ecosystem is in a much better place now, and so there's no need for hacks anymore. 

## How do I defer rendering in Next.js?

Next.js doesn't provide any hook modules, like `_app.js` they used to, so you have to defer the rendering on React's level, unfortunately. Here's an example of how to do that:

```js
function AppProvider() {
  const [isMockingEnabled, setMockingEnabled] = useState(false)

  useEffect(() => {
    registerMockServiceWorker().then(() => {
      setMockingEnabled(true)
    })
  }, [])

  if (!isMockingEnabled) {
    return null
  }

  return <YourApp />
}
```

Note that this isn't a solution inherent to MSW. Take a look at the [Remix example](https://github.com/mswjs/examples/blob/652a2cc6877d893237530436eba3283973880f05/examples/with-remix/app/entry.client.tsx#L20), which gives you the `entry.client.tsx` module to defer the rendering in a clean way, _outside_ of your React app.

**Comment by nareshbhatia** [comment]
@kettanaito, thanks so much for clarifying how msw is intended to be used and the workaround for next.js. I have modified my example accordingly and it is now working smoothly with msw 2.1.0.

Specifically, I simplified `AppProvider` a bit by creating a `useMockServiceWorker` hook. Please see the modified code below and let me know if there are any further suggestions:

[AppProvider.tsx](https://github.com/nareshbhatia/graphql-fragments-example-1/blob/main/src/providers/AppProvider.tsx#L11-L22)
```tsx
export function AppProvider({ children }: AppProviderProps) {
  const hasWorkerStarted = useMockServiceWorker();
  if (!hasWorkerStarted) {
    return undefined;
  }

  return (
    <ThemeProvider>
      <ApolloProvider>{children}</ApolloProvider>
    </ThemeProvider>
  );
}
```
[useMockServiceWorker.ts](https://github.com/nareshbhatia/graphql-fragments-example-1/blob/main/src/providers/useMockServiceWorker.ts)
```tsx
import * as React from 'react';

export function useMockServiceWorker() {
  const [hasWorkerStarted, setWorkerStarted] = React.useState(false);

  React.useMemo(() => {
    if (typeof window === 'object') {
      const { worker } = require('@/mocks/browser');
      worker.start({ onUnhandledRequest: 'bypass' }).then(() => {
        setWorkerStarted(true);
      });
    } else {
      setWorkerStarted(true);
    }
  }, []);

  return hasWorkerStarted;
}
```

**Comment by kettanaito** [comment]
@nareshbhatia, simply fantastic! Thank you for understanding.

**Comment by nareshbhatia** [comment]
@kettanaito, I am finding some issues with the above solution. It seems that the race conditions are still there.

This is what I did. I added a second page to the app, which just renders "Hello World". It does not make any API calls.

![image](https://github.com/mswjs/msw/assets/1220198/8454ee39-5bca-4c76-89cb-b22d3811f7af)

When I navigate to this page from the home page, it renders correctly. However, if I point my browser to this page directly (`http://localhost:3000/hello`), then the content renders twice! See below:

![image](https://github.com/mswjs/msw/assets/1220198/611d5ea3-1f89-4c9b-a92d-1daf24d325c8)

Not sure where to go from here. The updated code is [here](https://github.com/nareshbhatia/graphql-fragments-example-1/blob/main/src/app/hello/page.tsx). It's very simple - no magic.

P.S. Has anyone talked to next.js to provide a hook for service workers?

**Comment by nareshbhatia** [comment]
Ok, issue solved! I had to replace `useMemo` with `useEffect`. I have no idea why `useMemo` didn't work – hope someone can explain.

Anyway, [here's the fix](https://github.com/nareshbhatia/graphql-fragments-example-1/blob/main/src/providers/useMockServiceWorker.ts#L6).

**Comment by kettanaito** [comment]
Yeah, those look like React usage issues. MSW doesn't affect the rendering in any way. The worker promise should resolve when the worker is ready, and that's where MSW's responsibilities end, really.
