### ISSUE TITLE
Request with FormData body makes Jest hang forever

### ISSUE THREAD

**Issue by louislebrault** [kettanaito/msw#2078]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v21.5.0

### Reproduction repository

https://github.com/louislebrault/msw-formdata-graphql

### Reproduction steps

"yarn test"

### Current behavior

Jest is not exiting after running test and displays this warning :

```
Jest did not exit one second after the test run has completed.

'This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

### Expected behavior

Jest should be able to exit gracefully after running tests.

**Comment by louislebrault** [comment]
To add some context, formData is part of a convention concerning the implementation of file upload through a GraphQL API : https://github.com/jaydenseric/graphql-multipart-request-spec

**Comment by nzakas** [comment]
FWIW, the same problem exists when using a REST API. I'm using Mocha and my test won't exit if I POST using `FormData`. 

**Note:** A `FormData` object with no fields does not cause this problem, but as soon as you add a single field, the process hangs.

Here is a simple repo using Mocha and msw 2.2.3:
https://stackblitz.com/edit/stackblitz-starters-rprzyx?file=index.js

I tested all the way back to v2.0.0 and this same behavior is present.

**Comment by kettanaito** [comment]
Thanks for reporting this. There was a bug in Node.js v18 related to `FormData` but it was since fixed and should not be an issue on the latest v18.19.0. Wonder what makes this happen on Node.js v21.

It's worth noting MSW does nothing with `FormData`. It's likely that if something hangs, the issue is in the `FormData` itself. I recommend making sure you are not using any JSDOM and run a proper Node.js environment to A/B this behavior.

**Comment by kettanaito** [comment]
Note: interestingly, doesn't hang on Vitest.

**Comment by kettanaito** [comment]
## Root cause

This appears to be a bug in Node.js. If you run this in Node, no MSW involved, the process hangs forever on cloning the `Request` with a `FormData` body:

```js
const data = new FormData()
data.set('foo', 'ar')

const request = new Request('http://localhost', { method: 'POST', body: data })
request.clone()
console.log('cloned')
```

Replace the body with any other value, the request gets clone and the process exists normally. 

Reproducible on:
- v18.19.0
- v20.11.0
- v21.7.1

Filed as a bug in Node.js: https://github.com/nodejs/node/issues/52167. Please follow the resolution of that issue there. Thanks.

**Comment by kettanaito** [comment]
Also this: https://github.com/mswjs/msw/issues/1843 and this https://github.com/nodejs/undici/issues/2413.
