### ISSUE TITLE
Error: [MSW] Failed to locate the Service Worker registration.

### ISSUE THREAD

**Issue by radiantone** [kettanaito/msw#2163]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

...

### Reproduction steps

...

### Current behavior

In my webapp, msw service worker loads fine most of the time, but if I reload the app, check the console, and reload it a few times in a row, the error shows up intermittently. I checked loading the serviceworker script in chrome (served from NGINX btw) and never showed any problem reaching or loading the script.

### Expected behavior

To load the service worker script without claiming it failed to locate it.

**Comment by kettanaito** [comment]
Hi, @radiantone. Thanks for reporting this. 

Since you haven't provided a reproduction repository, all I can do is advise you to catch the scenario when you receive the error, and debug it yourself. See if the worker script `/mockServiceWorker.js` is served in that case. The error message you see also mentions a way to resolve this issue (using an explicit `serviceWorker.url` option in `worker.start()`. Try that.
