### ISSUE TITLE
Make bad "Network behavior overrides" more obvious

### ISSUE THREAD

**Issue by jgarplind** [kettanaito/msw#2167]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

This just happened:

I use MSW once in a while but not too often. I wanted to make a "Network behavior override" as defined here: https://mswjs.io/docs/best-practices/network-behavior-overrides

I made it, and it looked like this:

```js
    server.use(
      http.post("*", ({ request }) => {
        request.json().then((data) => {
          z.object({ title: z.literal(INPUT_TITLE) }).parse(data);
          return new HttpResponse(null, { status: 204 });
        });
      }),
    );
```

basically I wanted to make an assertion on the payload, and found this to be the most convenient way given my setup.

However, it did not behave as I expected. The test succeeded despite containing data designed to fail, but at least an "unexpected error" was thrown.

After quite some debugging, I found that _both_ my default handler _and_ my override was running, weird!

Turns out (duh), you need to add the `return` keyword like so:

```js
    server.use(
      http.post("*", ({ request }) => {
        return request.json().then((data) => {
          z.object({ title: z.literal(INPUT_TITLE) }).parse(data);
          return new HttpResponse(null, { status: 204 });
        });
      }),
    );
```

Still, this mistake was innocent, easy to make, took me a long time to discover, and caused unexpected behavior rather than failing early.

I'm not sure what could be done from the library perspective, but it would have helped me a lot if this was caught early somehow.

Thanks for reading!

**Comment by kettanaito** [comment]
Hi, @jgarplind. Thanks for raising this. 

I understand this might look inconvenient but MSW supports both cases that you have stumbled into by accident:

1. Returning a mocked response.
2. Returning nothing.

The library cannot warn you about the 2nd case because it's an _allowed case_. You can return nothing from a resolver if you wish to observe the request but do not modify it. You can also leverage that for fallthrough, executing multiple handlers for the same request until one of them actually handles it (returns a mocked response). 

> After quite some debugging, I found that both my default handler and my override was running, weird!

That was precisely what happened to you. That behavior was intentional. 

Following the [Debugging runbook](https://mswjs.io/docs/runbook) can help you spot what handlers are running (or not), and see _why_ (if multiple handlers are running for the same request, that means one or more of them did not return a mocked response). 

We shouldn't do anything about this scenario on the library's side.
