### ISSUE TITLE
Optional path parameters do not match correctly

### ISSUE THREAD

**Issue by GeorgeToka** [kettanaito/msw#2168]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

There is a [step](https://github.com/mswjs/msw/blob/d97a528914df6a656dfe7b1f63985c85845df533/src/core/utils/url/cleanUrl.ts#L7-L12) that drops query parameters and it looks like it breaks the ability to specify optional URL parameters, e.g `/api/user/:id?`.

The cleanup routine should be limited to removing the query parameters only.

**Comment by kettanaito** [comment]
Hi, @GeorgeToka. Thanks for reporting this!

The `cleanUrl` function you are referencing is applied to the _actual_ request URL. That one cannot have path parameter annotations, only the literal values of those parameters. 

But the issue you are describing is possible, the root cause may just be in a different place. We need an automated test to prove that.

**Comment by kettanaito** [comment]
I've added an automated test for this in https://github.com/mswjs/msw/pull/2169, and it seems to be failing, which is good! More investigation required.

**Comment by kettanaito** [comment]
## Released: v2.3.1 🎉

This has been released in v2.3.1!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.3.1)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.3.1)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by GeorgeToka** [comment]
@kettanaito Thanks for the quick turnaround on this one.
