### ISSUE TITLE
Uncaught TypeError: crypto.randomUUID is not a function at mockServiceWorker.js:114

### ISSUE THREAD

**Issue by jerrywu001** [kettanaito/msw#2292]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

xx

### Reproduction steps

Uncaught TypeError: crypto.randomUUID is not a function at mockServiceWorker.js:114

![image](https://github.com/user-attachments/assets/9d2f3421-78a0-49e1-90e0-5ad542540f69)

**Chrome 86**

### Current behavior

Uncaught TypeError: crypto.randomUUID is not a function at mockServiceWorker.js:114

![image](https://github.com/user-attachments/assets/9d2f3421-78a0-49e1-90e0-5ad542540f69)

**Chrome 86**

### Expected behavior

crypto.randomUUID can be found

**Comment by kettanaito** [comment]
Hi, @jerrywu001. Thanks for reporting this.

The `crypto` API is a global browser API. It's been supported in Chrome since v92 ([source](https://caniuse.com/mdn-api_crypto_randomuuid)). It looks like you are using an outdated version of Chrome (v86). Update your Chrome, and the issue will be gone.

If you cannot update your Chrome, downgrade to the version of MSW that doesn't rely on the global `crypto` module. Note that we aren't promising support of all browser versions. It'd be unreasonable for a devtool. But you can always assume the latest version of your browser should be supported.
