### ISSUE TITLE
Requests aren't intercepted anymore since 2.4.4

### ISSUE THREAD

**Issue by dbanck** [kettanaito/msw#2385]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v20.18.0

### Background

Thanks for this great library. We've been using it for some time now to mock response in the [vscode-terraform test suite](https://github.com/hashicorp/vscode-terraform/blob/main/src/test/e2e/specs/mocks/server.ts). 

During some [regular dependency bumps](https://github.com/hashicorp/vscode-terraform/pull/1899) we noticed that the mocking didn't work anymore.

### Reproduction repository

https://github.com/dbanck/playground-vscode-msw-bug

### Reproduction steps

* Open the reproduction repository with VSCode
* Run the extension (F5)
* Run the "hello world" command
![CleanShot 2024-12-06 at 15 24 58@2x](https://github.com/user-attachments/assets/22f9c435-053a-45ba-b2ad-ed843a5d1106)

### Current behavior

The request isn't intercepted anymore

The request isn't captured by any of the life-cycle events that log to the extension debug channel
![CleanShot 2024-12-06 at 15 25 28@2x](https://github.com/user-attachments/assets/fa504333-55cb-44d3-8f2e-8cb1e3ad832e)

Axios logs a 404 error, because the request isn't mocked and a real request is sent to `https://example.com/test`
![CleanShot 2024-12-06 at 15 26 06@2x](https://github.com/user-attachments/assets/5f6ef88a-ffa2-4b07-b99a-a6a22ad6d3a7)

### Expected behavior

I have traced it back to this change: https://github.com/mswjs/msw/compare/v2.4.3...v2.4.4

When I downgrade msw to 2.4.3 everything is working as expected. 

The request is logged by the lifecycle events
![CleanShot 2024-12-06 at 15 30 21@2x](https://github.com/user-attachments/assets/ec880ee8-f1af-42ac-8a93-45bb6bbb47b5)

And my mocked response is returned
![CleanShot 2024-12-06 at 15 30 36@2x](https://github.com/user-attachments/assets/62c9d947-1226-442e-bb30-014602b1dcf6)

**Comment by jmccure** [comment]
Noticed the same updating to 2.4.4 here https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/merge_requests/2188/diffs

**Comment by kettanaito** [comment]
Hi, @dbanck. Thanks for the detailed report. I will take a look at this once I have a moment.

**Comment by kettanaito** [comment]
## Discovery

The first thing I noticed is that replacing `axios.get` with `fetch` makes MSW intercept and handle that request just fine. So the issue is somewhere in how `axios.get` performs a request. Following this hunch, I configured Axios to use `fetch` as the underlying request mechanism, and that also fixed the issue:

```ts
const request = axios.create({
  adapter: 'fetch',
})

request
  .get('https://example.com/test') // OK!
```

In fact, using the `http` adapter reproduces the issue again, and that's where I assume it's used as the default adapter (since XHR is not available in VS Code extension context). 

## Root cause

The request is not intercepted because the reference to `http` (or `follow-redirects`'s reference to `http`, which is the default in axios) points to a different module than the one patched by `server.listen()`. As such, MSW cannot know about any calls to that different reference. 

We have both Axios and `follow-redirects` test cases passing, and this leads to me presume that the issue here is CommonJS bundling (likely the `.default.` chain). 

Swapping the import/require order of `axios` doesn't seem to make a difference.

**Comment by kettanaito** [comment]
Interestingly enough, when I inspect the `request.agent` on the Axios error, that's some different Agent than must be used with MSW:

<img width="996" alt="Screenshot 2024-12-16 at 13 04 46" src="https://github.com/user-attachments/assets/7a8659f3-8b68-413c-ab81-640b95620f8a" />

That may explain why, despite being constructed, the `MockHttpsAgent` is never called during this HTTPS request with Axios. `options.agent` is `undefined` when it's passed to `transport.request()` in Axios:

```js
// node_modules/axios/dist/node/axios.cjs
req = transport.request(options, function handleResponse(res) {
```

One more detail, `https.request` even _before_ patching by MSW is already patched by what I assume to be Axios:

```
https.request BEFORE patching: ƒ patched(url, options, callback) {
```

This is troubling because calling this `patched()` function never taps into the underlying Agent and its `createConnection()` method as Node.js does normally. In other words, we are patching a patch here and this is a no-op. 

~~I think the solution here is to force Axios out of that internal patching.~~

Looking closer at the `patched()` function, its origins is **vscode module itself**: https://github.com/microsoft/vscode/issues/120354. `vscode` seems to be patching `node:https` and its `https.request` function! 

Moreover, that patch seems to disregard any custom `options.agent` set, always forcing the `options.agent` to be the internal agent set by `vscode`:

```js
options.agent = agent;
```

> Unfortunately, the `patched()` function doesn't seem to be a part of the `vscode` package as I cannot find it in the source or in their GitHub repo.

## How to fix this?

@dbanck, given `vscode` meddles with Node.js internals, I recommend opting out from using `node:https` and use `fetch` instead, which they don't patch, allowing MSW to work properly.

**Comment by kettanaito** [comment]
Here's the entirety of the `patched()` function introduced by `vscode` for reference:

```js
patched(url, options, callback) {
            if (typeof url !== 'string' && !(url && url.searchParams)) {
                callback = options;
                options = url;
                url = null;
            }
            if (typeof options === 'function') {
                callback = options;
                options = null;
            }
            options = options || {};
            if (options.socketPath) {
                return original.apply(null, arguments);
            }
            const originalAgent = options.agent;
            if (originalAgent === true) {
                throw new Error('Unexpected agent option: true');
            }
            const isHttps = originals.globalAgent.protocol === 'https:';
            const optionsPatched = originalAgent instanceof agent_1.PacProxyAgent;
            const config = params.getProxySupport();
            const useProxySettings = !optionsPatched && (config === 'override' || config === 'fallback' || (config === 'on' && originalAgent === undefined));
            const addCertificatesV1 = !optionsPatched && params.addCertificatesV1() && isHttps && !options.ca;
            if (useProxySettings || addCertificatesV1) {
                if (url) {
                    const parsed = typeof url === 'string' ? new nodeurl.URL(url) : url;
                    const urlOptions = {
                        protocol: parsed.protocol,
                        hostname: parsed.hostname.lastIndexOf('[', 0) === 0 ? parsed.hostname.slice(1, -1) : parsed.hostname,
                        port: parsed.port,
                        path: `${parsed.pathname}${parsed.search}`
                    };
                    if (parsed.username || parsed.password) {
                        options.auth = `${parsed.username}:${parsed.password}`;
                    }
                    options = Object.assign(Object.assign({}, urlOptions), options);
                }
                else {
                    options = Object.assign({}, options);
                }
                const resolveP = (req, opts, url) => new Promise(resolve => resolveProxy({ useProxySettings, addCertificatesV1 }, req, opts, url, resolve));
                const host = options.hostname || options.host;
                const isLocalhost = !host || host === 'localhost' || host === '127.0.0.1'; // Avoiding https://github.com/microsoft/vscode/issues/120354
                const agent = (0, agent_1.default)(resolveP, {
                    originalAgent: (!useProxySettings || isLocalhost || config === 'fallback') ? originalAgent : undefined,
                    lookupProxyAuthorization: params.lookupProxyAuthorization,
                });
                agent.protocol = isHttps ? 'https:' : 'http:';
                options.agent = agent;
                return original(options, callback);
            }
            return original.apply(null, arguments);
        }
```

**Comment by kettanaito** [comment]
This wasn't an issue before because MSW's patch was more aggressive, overriding `http.request` altogether. With recent versions, we've migrated to a more permissive patch that allows more of the Node.js network code to run, which is beneficial on all accounts. As a side-effect of this change, MSW now expects the underlying code to be even more Node.js-compatible, having no patches whatsoever.
