### ISSUE TITLE
ctx.json doesn't accept number as the value

### ISSUE THREAD

**Issue by radoslawgrochowski** [kettanaito/msw#920]
## Describe the bug
`rest` methods doesn't accept `number` as type parameter for `RequestBodyType` or `ResponseBody` due do extending `DefaultRequestBody`:
```ts
export declare type DefaultRequestBody = Record<string, any> | DefaultRequestMultipartBody | string | undefined;
```
https://github.com/mswjs/msw/blob/master/src/handlers/RequestHandler.ts#L24
## Environment

- `msw: 0.34.0`
- `tsc: 4.3.5`

## To Reproduce
```ts
import { rest } from 'msw';

rest.post<string, number>('/api', (_, response, context) => {
  response(context.status(200));
});

>>  error TS2344: Type 'number' does not satisfy the constraint 'DefaultRequestBody'.

```

## Expected behavior
no  error TS2344 on reproduction snippet above

**Comment by kettanaito** [comment]
Hey, @radoslawgrochowski.

I'm not sure I understand what's your expected behavior is.

- Request/response bodies _cannot_ be numbers. All HTTP transaction bodies are _strings_, even if they represent numbers.

Any mocked response, just as any real HTTP response, is a string. That's why you stringify non-string data like JSON before sending it. That is why the respective TypeScript declarations for the request/response body (such as `RequestBodyType` and `ResponseBodyType`) extend _string_ and some arbitrary string-compatible types because they may be stringified for you in context methods like `ctx.json`. There is no convenient method just for strings, so if your mocked response body is expected to be a single integer, you have to convert it to string manually. 

If you wish to respond with a number in your mocked response, stringify it before doing so:

```js
rest.post<string, number>('/api', (_, response, context) => {
  const number = 2
  response(context.status(200), context.body(number.toString());
});
```

> Don't forget to use the `context.body` utility if you wish to specify a mocked response body. It's missing in your example above, you're only responding with a 200 OK response with an empty body. 

If a number is a part of your mocked response JSON, then it can be passed as-is using the `ctx.json` utility.

**Comment by radoslawgrochowski** [comment]
Thanks for reply, @kettanaito 

> Any mocked response, just as any real HTTP response, is a string.
I mean the typings that represent JSON content.

Your snippet code gives me typescript error. Current typings disallow `number` as top level `application/json` response - which is valid.

If i understand correctly: https://www.ietf.org/rfc/rfc7159.txt 
> A JSON text is a sequence of tokens.  The set of tokens includes six
   structural characters, strings, numbers, and three literal names.
   
Reproduction:
https://codesandbox.io/s/sharp-mcnulty-78lfy?file=/src/index.ts
```
import { rest } from "msw";

rest.post<string, number>('/api', (_, response, context) => {
  response(context.status(200), context.json(2));
});
//above: >>  error TS2344: Type 'number' does not satisfy the constraint 'DefaultRequestBody'.

rest.post<string, { a: number }>('/api2', (_, response, context) => {
  response(context.status(200), context.json({ a: 2 }));
});
//works, even tho its not a string
```
