### ISSUE TITLE
@vue/apollo-composables useQuery doesn't get intercepted

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [kettanaito/msw#937]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.35.0   |
| node | 14.17.3|
| OS   | Windows 10 10.0.19042     |

## Request handlers

```js
// Example of declaration. Provide your code here.
import { setupServer } from 'msw/node'
import { graphql } from 'msw'

const middleware = graphql.link('http://localhost:3000/graphql');
const handlers = [
  middleware.query('test1', (req, res, ctx) => {
    return res(
      ctx.data({
         prop1: [{
           prop2: [{
              prop3: 'text',
              prop4: 1234
            },
              prop3: 'text',
              prop4: 1234
            }]
         }]
      })
    );
  }),
  middleware.query('test2', (req, res, ctx) => {
    return res(
      ctx.data({
         prop1: {
           prop2: 1
         }
      })
    );
  }),
];

const server = setupServer(...handlers);

describe('<testsuite1>', () => {
  beforeAll(() => {
    server.listen();
  });

  beforeEach(() => {
    apolloClient.clearStore();
  });

  afterEach(() => {
    server.resetHandlers();
  });

  afterAll(() => {
    server.close();
  });
});

```

## Actual request

```js
const test2 = gql`
  query test2 {
    prop1 {
      prop2
    }
  }
`;
// Example of making a request. Provide your code here.
const { result } = useQuery(test2);
```

## Current behavior

No graphql queries are being intercepted. I used vscode to set a breakpoint within the handlers and handler registration but there was no break at all.

## Expected behavior

Graphql queries are being intercepted and the custom response is returned

**Comment by kettanaito** [comment]
Hey, @sschneider-ihre-pvs.

The setup you've included looks correct. You did, however, omit the most important parts:

- How the actual request is made.
- How your request handler looks like (without the pseudo-code).

These two areas may include a lot of potential issues: typos in the operation names or endpoints, incorrect requests, response resolvers that don't return anything. It's virtually impossible for me to suggest anything without that concretics. 

I highly encourage you to create a minimal reproduction repository and link it here. You can use one of the [existnig examples](https://github.com/mswjs/examples/tree/master/examples) as a starting point. When isolating the issue in a clean environment you have a solid chance of finding the root cause yourself. If you still don't, link that reproduction repository here, and I, or other volunteers, will be happy to look at it. 

I'll close the issue until you can reproduce it in a standalone repository.

**Comment by sschneider-ihre-pvs** [comment]
does this help?

**Comment by kettanaito** [comment]
@sschneider-ihre-pvs, thanks for updating the description. If you could please prepare a reproduction repository that'd be top-notch. The description alone is not a verification that the issue is there, and doesn't give enough means to reproduce it.
