### ISSUE TITLE
GraphQL POST request parsing fails with string body

### ISSUE THREAD

**Issue by ianschmitz** [kettanaito/msw#957]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.35.0   |
| node | 14.17.3     |
| OS   | macOS 11.6     |

## Request handlers

```js
// Example of declaration. Provide your code here.
import { setupServer } from 'msw/node'
import { rest } from 'msw'

const server = setupServer(
   graphql.query(
            "MyActivityTagUsagesLast",
            (req, res, ctx) => {
                return res(
                    ctx.data({
                        ...
                    }),
                );
            },
        )
)

server.listen()
```

## Actual request

```js
// Example of making a request. Provide your code here.
const res = await fetch("/v1/graphql", {
    method: "POST",
      body: JSON.stringify({ query, variables }),
    });
```

## Current behavior

GraphQL requests are not being intercepted. During debugging i traced it back to this check here that expects the body to be an object, not a string: https://github.com/mswjs/msw/blob/a9085a670d03401a8e7ed05547ba2e5af09c401f/src/utils/internal/parseGraphQLRequest.ts#L102

However what is being checked by MSW looks like the following - note the `body` is a string:

```json
{
  "id": "9a3588f2-9da0-44cb-b9c8-b4f3de113353",
  "url": "http://localhost/v1/graphql",
  "method": "POST",
  "body": "{\"query\":\"\\n    query MyActivityTagUsagesLast($employeeId: bigint!) {\\n  tagUsages(\\n    where: {employee: {id: {_eq: $employeeId}}}\\n    order_by: {date: desc}\\n    limit: 1\\n  ) {\\n    date\\n  }\\n}\\n    \",\"variables\":{\"employeeId\":1}}",
  "headers": {
    "_headers": {
      "content-type": "text/plain;charset=UTF-8",
      "x-msw-request-id": "9a3588f2-9da0-44cb-b9c8-b4f3de113353",
      "cookie": ""
    },
    "_names": {}
  },
  "cookies": {},
  "redirect": "manual",
  "referrer": "",
  "keepalive": false,
  "cache": "default",
  "mode": "cors",
  "referrerPolicy": "no-referrer",
  "integrity": "",
  "destination": "document",
  "bodyUsed": false,
  "credentials": "same-origin"
}
```

## Expected behavior

Expected string `body` to work as expected as this is the recommended way to send JSON in the body of a POST request using fetch: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#uploading_json_data

**Comment by kettanaito** [comment]
Hey, @ianschmitz.

## Solution

Your POST request is missing the `Content-Type` header to specify that its body is a JSON string. Citing the MDN page you've referenced:

```diff
fetch('https://example.com/profile', {
  method: 'POST', // or 'PUT'
+ headers: {
+   'Content-Type': 'application/json',
+ },
  body: JSON.stringify(data),
})
```

Once you add that header, MSW will correctly parse the response body, see that it has the `query` property, and passes the aforementioned condition:

https://github.com/mswjs/msw/blob/a9085a670d03401a8e7ed05547ba2e5af09c401f/src/utils/internal/parseGraphQLRequest.ts#L102

This will continue the process of GraphQL request parsing, determining the validity of the query using `graphql-js` package. 

## Background

Think of MSW as of actual HTTP server. If you dispatched such POST request to a real server, it would not attempt to parse the response body as JSON because you're not telling it to (not specifying the `Content-Type`). It'd treat that body as a string, just like MSW does above. 

## GraphQL specification compliance

GraphQL specification states that a GraphQL server supports two ways of requests:

1. `GET` with the `query` included in the query parameters as a string.
2. `POST` with the `query` included in the _JSON_ response body.

**Comment by ianschmitz** [comment]
That's what i get for debugging late on a Friday 🤪

Since i was using GraphQL Code Generator with the [typescript-react-query](https://www.graphql-code-generator.com/docs/plugins/typescript-react-query) plugin, i had to add this to my codegen config:


```json
"fetchParams": "{ headers: {\"Content-Type\": \"application/json\"} }"
```

I hadn't noticed this previously since my GraphQL endpoint (Hasura) worked fine with a text/plain `Content-Type`.
